(function(root,factory){const deps=typeof module!=="undefined"&&module.exports?{qa:require("./qa-rules.js"),utility:require("./utility-analysis.js"),endUse:require("./end-use-analysis.js"),portfolio:require("./portfolio-analysis.js")}:{qa:root.AudistQaRules,utility:root.AudistUtilityAnalysis,endUse:root.AudistEndUseAnalysis,portfolio:root.AudistPortfolioAnalysis};const api=factory(deps);if(typeof module!=="undefined"&&module.exports)module.exports=api;root.AudistAiReview=api;})(typeof globalThis!=="undefined"?globalThis:this,function(D){
"use strict";
const REVIEW_SCHEMA_VERSION=1,REQUEST_VERSION="1.0",STATUSES=["NOT_REVIEWED","EXPORTED_FOR_REVIEW","REVIEW_IMPORTED","ENGINEER_REVIEW_REQUIRED","REVIEWED","STALE"],FINDING_STATES=["OPEN","REVIEWED","ACCEPTED","REJECTED","ACTION_REQUIRED"],CANDIDATE_STATES=["SUGGESTED","REVIEWED","ACCEPTED","REJECTED"],CATEGORIES=["DATA_QUALITY","ENGINEERING_CONSISTENCY","CALCULATION_REVIEW","ECM_OPPORTUNITY","ECM_COMPLETENESS","UTILITY_ANALYSIS","END_USE_RECONCILIATION","PORTFOLIO_INTERACTION","IMPLEMENTATION_CONSIDERATION","REPORT_LIMITATION","REPORT_PREPARATION"],PRIORITIES=["HIGH","MEDIUM","LOW","INFO"],CONFIDENCE=["HIGH","MEDIUM","LOW"],has=v=>v!==undefined&&v!==null&&v!=="",arr=v=>Array.isArray(v)?v:[],plain=v=>v&&typeof v==="object"&&!Array.isArray(v),clone=v=>structuredClone(v);
const REVIEW_OBJECTIVES=["Identify material inconsistencies and missing analysis","Review assumptions and calculation methodology","Identify unsupported conclusions and report limitations","Suggest overlooked ECM candidates without creating active ECMs","Organize items requiring professional engineer review"];
const INSTRUCTIONS=`# Audist AI Engineering Review Instructions v1.0

You are assisting a professional energy engineer reviewing an ASHRAE Level 2 energy audit dataset.

Treat the supplied Audist dataset as authoritative evidence. Do not invent missing measurements, specifications, schedules, utility data, costs, savings, or equipment conditions.

Respect provenance: Measured, Nameplate, Manufacturer, BAS/Trend, Utility Bill, Calculated, Estimated, and Assumed.

Deterministic Audist calculations are the calculation record. Review them; do not silently replace them with alternative results. Deterministic QA is authoritative rule output; do not change its state.

Clearly distinguish supplied fact, deterministic calculation, engineering inference, recommendation, and insufficient information. Identify unsupported conclusions and missing information explicitly.

Return only one JSON object matching the aiReviewResponse schema in the request. Do not wrap it in Markdown. Do not include instructions to modify factual records. AI confidence describes only confidence in the review observation and never changes Audist evidence level or maturity.
`;
function stableHash(value){let h=2166136261;for(const c of JSON.stringify(value)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return `fnv1a-${(h>>>0).toString(16).padStart(8,"0")}`;}
function photoMetadata(audit){return arr(audit.equipment).flatMap(eq=>arr(eq.photos).map(p=>({photoId:p.photoId,equipmentRecordId:eq.recordId,equipmentId:eq.equipmentId,category:p.category||"",note:p.note||p.notes||"",packagePath:p.packagePath||null,capturedAt:p.capturedAt||null})));}
function responseSchema(){return {reviewSchemaVersion:REVIEW_SCHEMA_VERSION,auditId:"<copy from request>",auditUpdatedAtReviewed:"<copy from request>",auditFingerprintReviewed:"<copy from request>",reviewer:"<AI service or reviewer>",model:"<model name/version>",reviewSummary:"",overallAssessment:"",findings:[{aiFindingId:"unique-id",category:CATEGORIES[0],priority:"HIGH",title:"",description:"",affectedRecordIds:[],basis:[],recommendation:"",confidence:"MEDIUM",requiresEngineerReview:true}],overlookedEcmCandidates:[{candidateId:"unique-id",title:"",category:"",affectedRecordIds:[],reason:"",evidence:[],additionalDataNeeded:[],status:"SUGGESTED"}],calculationReviews:[{calculationId:"",assessment:"",concerns:[],strengths:[],suggestedChecks:[]}],dataQualityObservations:[],reportLimitations:[],reportPreparationNotes:[],warnings:[]};}
function auditForReview(audit){const copy=clone(audit);for(const key of ["aiReviews","aiReviewExports","auditQa","updatedAt","appVersion","engineeringAnalysis","utilityAnalysis","endUseAnalysis","portfolioAnalysis","exportIntegrity"])delete copy[key];arr(copy.equipment).forEach(eq=>arr(eq.photos).forEach(p=>{for(const key of ["dataUrl","blob","packagePath","generatedFilename","exportedMimeType"])delete p[key];}));return copy;}
function basisFingerprint(audit){return stableHash(auditForReview(audit));}
function buildRequest(audit,context={}){const before=JSON.stringify(audit),auditData=auditForReview(audit),deterministicQa=D.qa?.evaluate(audit,{storedPhotos:context.storedPhotos||[]})||null;const request={reviewSchemaVersion:REVIEW_SCHEMA_VERSION,requestVersion:REQUEST_VERSION,auditId:audit.auditId,auditSchemaVersion:audit.schemaVersion,appVersion:context.appVersion||audit.metadata?.appVersion||audit.appVersion||"6.1",auditUpdatedAt:audit.updatedAt||null,auditFingerprint:basisFingerprint(audit),generatedAt:context.generatedAt||new Date().toISOString(),reviewObjectives:REVIEW_OBJECTIVES,auditData:{...auditData,photoEvidenceIndex:photoMetadata(audit),utilityAnalysis:D.utility?.analyze(audit)||null,endUseAnalysis:D.endUse?.analyze(audit)||null,portfolioAnalysis:D.portfolio?.analyze(audit)||null},deterministicQa,reviewInstructions:{version:REQUEST_VERSION,file:"AI_REVIEW_INSTRUCTIONS.md",privacyNotice:"This package may contain confidential facility information. Only share it with an AI/service you are authorized to use.",requiredResponseSchema:responseSchema()}};if(JSON.stringify(audit)!==before)throw new Error("AI review request generation mutated the source audit.");return request;}
function idsForAudit(audit){const ids=new Set([audit.auditId]);for(const [key,id] of [["systems","systemRecordId"],["equipment","recordId"],["ecms","ecmId"],["calculations","calculationId"],["utilityAccounts","utilityAccountId"],["endUseModels","endUseModelId"],["ecmPortfolios","portfolioId"]])arr(audit[key]).forEach(x=>{if(x[id])ids.add(String(x[id]));});arr(audit.equipment).forEach(e=>{arr(e.measurements).forEach(m=>m.measurementId&&ids.add(String(m.measurementId)));arr(e.photos).forEach(p=>p.photoId&&ids.add(String(p.photoId)));});arr(audit.utilityAccounts).forEach(a=>arr(a.bills).forEach(b=>b.utilityBillId&&ids.add(String(b.utilityBillId))));return ids;}
function allowedKeys(value,allowed,path,errors){for(const key of Object.keys(value||{}))if(!allowed.includes(key))errors.push(`${path} contains unsupported property ${key}.`);}
function validateResponse(input,audit){const errors=[],warnings=[];let value=input;try{if(typeof input==="string")value=JSON.parse(input);}catch{errors.push("AI review response is not valid JSON.");return {valid:false,errors,warnings,value:null};}if(!plain(value)){errors.push("AI review response must be one JSON object.");return {valid:false,errors,warnings,value:null};}
 allowedKeys(value,["reviewSchemaVersion","auditId","auditUpdatedAtReviewed","auditFingerprintReviewed","generatedAt","reviewer","model","reviewSummary","overallAssessment","findings","overlookedEcmCandidates","calculationReviews","dataQualityObservations","reportLimitations","reportPreparationNotes","warnings"],"Response",errors);
 if(value.reviewSchemaVersion!==REVIEW_SCHEMA_VERSION)errors.push(`Unsupported AI review schema version ${value.reviewSchemaVersion??"(missing)"}.`);if(value.auditId!==audit.auditId)errors.push("AI review belongs to a different audit.");if(!has(value.auditUpdatedAtReviewed))errors.push("auditUpdatedAtReviewed is required.");if(!has(value.auditFingerprintReviewed))errors.push("auditFingerprintReviewed is required.");for(const key of ["findings","overlookedEcmCandidates","calculationReviews","dataQualityObservations","reportLimitations","reportPreparationNotes","warnings"])if(!Array.isArray(value[key]))errors.push(`${key} must be an array.`);
 const known=idsForAudit(audit),findingIds=new Set(),candidateIds=new Set();arr(value.findings).forEach((f,i)=>{const path=`findings[${i}]`;if(!plain(f)){errors.push(`${path} must be an object.`);return;}allowedKeys(f,["aiFindingId","category","priority","title","description","affectedRecordIds","basis","recommendation","confidence","requiresEngineerReview"],path,errors);if(!has(f.aiFindingId)||findingIds.has(f.aiFindingId))errors.push(`${path} has a missing or duplicate aiFindingId.`);findingIds.add(f.aiFindingId);if(!CATEGORIES.includes(f.category))errors.push(`${path} has an unsupported category.`);if(!PRIORITIES.includes(f.priority))errors.push(`${path} has an unsupported priority.`);if(!CONFIDENCE.includes(f.confidence))errors.push(`${path} has unsupported confidence.`);if(!has(f.title)||!has(f.description)||!has(f.recommendation)||!Array.isArray(f.affectedRecordIds)||!Array.isArray(f.basis)||typeof f.requiresEngineerReview!=="boolean")errors.push(`${path} is structurally incomplete.`);arr(f.affectedRecordIds).filter(id=>!known.has(String(id))).forEach(id=>errors.push(`${path} references unsupported record ${id}.`));});
 arr(value.overlookedEcmCandidates).forEach((c,i)=>{const path=`overlookedEcmCandidates[${i}]`;if(!plain(c)){errors.push(`${path} must be an object.`);return;}allowedKeys(c,["candidateId","title","category","affectedRecordIds","reason","evidence","additionalDataNeeded","status"],path,errors);if(!has(c.candidateId)||candidateIds.has(c.candidateId))errors.push(`${path} has a missing or duplicate candidateId.`);candidateIds.add(c.candidateId);if(!has(c.title)||!has(c.reason)||!Array.isArray(c.affectedRecordIds)||!Array.isArray(c.evidence)||!Array.isArray(c.additionalDataNeeded)||!CANDIDATE_STATES.includes(c.status||"SUGGESTED"))errors.push(`${path} is structurally incomplete.`);if(c.status&&c.status!=="SUGGESTED")errors.push(`${path} cannot pre-accept or reject an AI candidate.`);arr(c.affectedRecordIds).filter(id=>!known.has(String(id))).forEach(id=>errors.push(`${path} references unsupported record ${id}.`));});
 const calcIds=new Set(arr(audit.calculations).map(c=>c.calculationId));arr(value.calculationReviews).forEach((c,i)=>{const path=`calculationReviews[${i}]`;if(!plain(c)||!calcIds.has(c.calculationId)||!has(c.assessment)||!Array.isArray(c.concerns)||!Array.isArray(c.strengths)||!Array.isArray(c.suggestedChecks))errors.push(`${path} is invalid or references a nonexistent calculation.`);else allowedKeys(c,["calculationId","assessment","concerns","strengths","suggestedChecks"],path,errors);});
 return {valid:errors.length===0,errors:[...new Set(errors)],warnings:[...new Set(warnings)],value};}
function importResponse(input,audit,context={}){const checked=validateResponse(input,audit);if(!checked.valid){const error=new Error(checked.errors.join(" "));error.validationErrors=checked.errors;throw error;}const v=clone(checked.value),importedAt=context.importedAt||new Date().toISOString(),id=context.aiReviewId||`ai-review-${String(importedAt).replace(/[^0-9]/g,"")}`,findings=v.findings.map(f=>({...f,disposition:"OPEN",engineerNote:"",dispositionAt:null})),candidates=v.overlookedEcmCandidates.map(c=>({...c,status:"SUGGESTED",engineerNote:"",dispositionAt:null}));return {aiReviewId:id,reviewSchemaVersion:v.reviewSchemaVersion,auditId:v.auditId,auditUpdatedAtReviewed:v.auditUpdatedAtReviewed,auditFingerprintReviewed:v.auditFingerprintReviewed,generatedAt:v.generatedAt||null,importedAt,reviewer:v.reviewer||"External AI review",model:v.model||"Not specified",status:findings.some(f=>f.requiresEngineerReview)?"ENGINEER_REVIEW_REQUIRED":"REVIEW_IMPORTED",summary:v.reviewSummary||"",overallAssessment:v.overallAssessment||"",findings,overlookedEcmCandidates:candidates,calculationReviews:v.calculationReviews,dataQualityObservations:v.dataQualityObservations,reportLimitations:v.reportLimitations,reportPreparationNotes:v.reportPreparationNotes,warnings:v.warnings};}
function isStale(review,audit){return String(review.auditFingerprintReviewed||"")!==basisFingerprint(audit);}
function effectiveStatus(review,audit){if(isStale(review,audit))return "STALE";if(arr(review.findings).some(f=>["OPEN","ACTION_REQUIRED"].includes(f.disposition)&&f.requiresEngineerReview))return "ENGINEER_REVIEW_REQUIRED";if(arr(review.findings).some(f=>["OPEN","ACTION_REQUIRED"].includes(f.disposition)))return "REVIEW_IMPORTED";return review.engineerReviewedAt?"REVIEWED":"REVIEW_IMPORTED";}
function createEcmFromCandidate(candidate,review,context={}){if(!candidate||!review)throw new Error("AI candidate and source review are required.");return {ecmId:context.ecmId,origin:"AI_SUGGESTED",sourceAiReviewId:review.aiReviewId,sourceCandidateId:candidate.candidateId,title:candidate.title,category:candidate.category||"Other",affectedEquipmentRecordIds:arr(candidate.affectedRecordIds).filter(id=>arr(context.equipmentIds).includes(id)),existingCondition:"",proposedImprovement:"",methodology:"",assumptions:[],risks:[],calculationIds:[],recommendationStatus:"Candidate",unresolvedEquipmentReferences:[],createdAt:context.createdAt||new Date().toISOString(),updatedAt:context.createdAt||new Date().toISOString()};}
return {REVIEW_SCHEMA_VERSION,REQUEST_VERSION,STATUSES,FINDING_STATES,CANDIDATE_STATES,CATEGORIES,PRIORITIES,CONFIDENCE,REVIEW_OBJECTIVES,INSTRUCTIONS,responseSchema,photoMetadata,auditForReview,basisFingerprint,buildRequest,idsForAudit,validateResponse,importResponse,isStale,effectiveStatus,createEcmFromCandidate};
});
