(function(root,factory){const endUse=typeof module!=="undefined"&&module.exports?require("./end-use-analysis.js"):root.AudistEndUseAnalysis,portfolio=typeof module!=="undefined"&&module.exports?require("./portfolio-analysis.js"):root.AudistPortfolioAnalysis,api=factory(endUse,portfolio);if(typeof module!=="undefined"&&module.exports)module.exports=api;root.AudistPackageExport=api;})(typeof globalThis!=="undefined"?globalThis:this,function(END_USE_ANALYSIS,PORTFOLIO_ANALYSIS){
"use strict";
const PACKAGE_FORMAT_VERSION=5,enc=new TextEncoder();
const has=v=>v!==undefined&&v!==null&&v!=="";
function safeName(value,fallback="item"){const text=String(value||"").normalize("NFKC").replace(/[\\/:*?"<>|\x00-\x1f]/g,"_").replace(/\.\.+/g,"_").replace(/[^\p{L}\p{N}._ -]+/gu,"_").replace(/[ .]+$/g,"").replace(/\s+/g,"_").replace(/_+/g,"_").slice(0,80);return text&&!/^_+$/.test(text)&&text!=="."&&text!==".."?text:fallback;}
function csvCell(value){if(value===undefined||value===null)return "";const s=typeof value==="object"?JSON.stringify(value):String(value);return /[",\r\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;}
function csv(headers,rows){return "\ufeff"+[headers.join(","),...rows.map(row=>headers.map(h=>csvCell(row[h])).join(","))].join("\r\n")+"\r\n";}
function outputSummary(calc){return (calc.outputs||[]).map(o=>`${o.displayName||o.parameterId}: ${o.value} ${o.unit||""}`.trim()).join("; ");}
function tables(audit,readiness=[]){const equipmentById=new Map((audit.equipment||[]).map(e=>[e.recordId,e])),readyById=new Map(readiness.map(r=>[r.ecmId,r]));
 const systemsHeaders=["systemRecordId","systemId","systemType","name","status","operatingSchedule","controlsSummary","notes"],systems=(audit.systems||[]).map(s=>Object.fromEntries(systemsHeaders.map(h=>[h,s[h]??(h==="operatingSchedule"?s.schedule:h==="controlsSummary"?s.controls:"")])));
 const equipmentHeaders=["recordId","equipmentId","systemRecordId","systemType","equipmentSubtype","status","manufacturer","model","capacity","ratedHp","quantity","existingWatts","hoursAnnual","notes"],equipment=(audit.equipment||[]).map(e=>Object.fromEntries(equipmentHeaders.map(h=>[h,e[h]??""])));
 const measurementHeaders=["measurementId","equipmentRecordId","equipmentId","parameter","value","numericValue","unit","provenance","method","instrument","notes","capturedAt"],measurements=[];(audit.equipment||[]).forEach(e=>(e.measurements||[]).forEach(m=>measurements.push({measurementId:m.measurementId,equipmentRecordId:e.recordId,equipmentId:e.equipmentId,parameter:m.parameter,value:m.value,numericValue:m.numericValue??(Number.isFinite(Number(m.value))?Number(m.value):""),unit:m.unit,provenance:m.provenance||m.source,method:m.method,instrument:m.instrument,notes:m.notes,capturedAt:m.capturedAt})));
 const utilityHeaders=["utilityAccountId","utilityBillId","utilityType","provider","accountLabel","meterNumber","rateSchedule","billingStartDate","billingEndDate","billingDays","usage","usageUnit","peakDemandKw","cost","energyCost","demandCost","fixedCharges","taxesOther","estimatedBill","source","notes"],utilities=[];(audit.utilityAccounts||[]).forEach(a=>(a.bills||[]).forEach(b=>utilities.push({...Object.fromEntries(utilityHeaders.map(h=>[h,b[h]??a[h]??""])),utilityType:a.utilityType,provider:a.provider,accountLabel:a.accountLabel,meterNumber:a.meterNumber,rateSchedule:a.rateSchedule})));if(!utilities.length)(audit.utility?.months||[]).forEach(u=>utilities.push({utilityAccountId:u.accountId,utilityBillId:u.utilityMonthId,utilityType:"Legacy",meterNumber:u.meterId,billingEndDate:u.month,usage:u.kWh??u.therms,usageUnit:u.kWh!==undefined?"kWh":"therms",peakDemandKw:u.kw??u.peakKw,cost:u.electricCost??u.gasCost,notes:u.notes}));
 const ecmHeaders=["ecmId","title","category","affectedEquipmentIds","existingCondition","proposedImprovement","fieldDocumentationStatus","engineeringReadinessStatus","confidence","annualEnergySavings","demandSavings","fuelSavings","costSavings","implementationCost","simplePaybackYears","calculationIds"],ecms=(audit.ecms||[]).map(e=>{const r=readyById.get(e.ecmId);return {ecmId:e.ecmId,title:e.title,category:e.category,affectedEquipmentIds:(e.affectedEquipmentRecordIds||[]).map(id=>equipmentById.get(id)?.equipmentId||id).join("; "),existingCondition:e.existingCondition||e.existing,proposedImprovement:e.proposedImprovement||e.proposed,fieldDocumentationStatus:r?.fieldDataComplete===false?"INCOMPLETE":"COMPLETE",engineeringReadinessStatus:r?.status||"",confidence:e.confidence,annualEnergySavings:e.savings?.annualEnergySavings??e.annualEnergySavings,demandSavings:e.savings?.demandSavings??e.demandSavings,fuelSavings:e.savings?.fuelSavings??e.fuelSavings,costSavings:e.savings?.costSavings??e.costSavings,implementationCost:e.implementationCost,simplePaybackYears:e.simplePaybackYears,calculationIds:(e.calculationIds||[]).join("; ")};});
 const calculationHeaders=["calculationId","methodId","methodVersion","ecmId","maturity","evidenceLevel","status","outputs","assumptionsCount","qaFlagCount","calculatedAt","staleStatus"],calculations=(audit.calculations||[]).map(c=>({calculationId:c.calculationId,methodId:c.methodId,methodVersion:c.methodVersion,ecmId:c.ecmId,maturity:c.maturity,evidenceLevel:c.evidenceLevel,status:c.status,outputs:outputSummary(c),assumptionsCount:(c.assumptions||[]).length,qaFlagCount:(c.qaFlags||[]).length,calculatedAt:c.calculatedAt,staleStatus:c.status==="Needs Recalculation"?"STALE":"CURRENT"}));
 const endUseHeaders=["endUseModelId","origin","utilityType","category","subcategory","annualEnergy","energyUnit","annualCost","provenance","evidenceLevel","maturity","status","sourceCalculationIds","systemRecordIds","equipmentRecordIds","assumptionsCount","warningsCount"],endUses=(audit.endUseAnalysis?.models||audit.endUseModels||[]).map(m=>({endUseModelId:m.endUseModelId,origin:m.origin,utilityType:m.utilityType,category:m.category,subcategory:m.subcategory,annualEnergy:m.annualEnergy,energyUnit:m.energyUnit,annualCost:m.annualCost,provenance:m.provenance,evidenceLevel:m.evidenceLevel,maturity:m.maturity,status:m.status,sourceCalculationIds:(m.calculationIds||[]).join("; "),systemRecordIds:(m.systemRecordIds||[]).join("; "),equipmentRecordIds:(m.equipmentRecordIds||[]).join("; "),assumptionsCount:(m.assumptions||[]).length,warningsCount:(m.warnings||[]).length}));
 const portfolioHeaders=["portfolioId","name","status","ecmIds","sequence","standaloneElectricKwh","adjustedElectricKwh","standaloneFuelTherms","adjustedFuelTherms","combinedCostSavings","combinedImplementationCost","simplePaybackYears","evidenceLevel","maturity","qaFlagCount"],portfolios=(audit.portfolioAnalysis?.portfolios||audit.ecmPortfolios||[]).map(p=>({portfolioId:p.portfolioId,name:p.name,status:p.status,ecmIds:(p.ecmIds||[]).join("; "),sequence:(p.sequence||[]).join("; "),standaloneElectricKwh:p.standaloneSavings?.electricKwh,adjustedElectricKwh:p.combinedSavings?.electricKwh,standaloneFuelTherms:p.standaloneSavings?.fuelTherms,adjustedFuelTherms:p.combinedSavings?.fuelTherms,combinedCostSavings:p.combinedCostSavings,combinedImplementationCost:p.combinedImplementationCost,simplePaybackYears:p.simplePaybackYears??p.combinedEconomics?.simplePaybackYears,evidenceLevel:p.evidenceLevel,maturity:p.maturity,qaFlagCount:(p.qaFlags||[]).length}));
 const interactionHeaders=["portfolioId","interactionId","ecmIds","interactionType","confirmed","affectedUtilityType","affectedEndUse","method","originalBaseline","combinedSavings","finalProposedEnergy","assumptions","warnings","engineerNotes"],interactions=(audit.portfolioAnalysis?.portfolios||audit.ecmPortfolios||[]).flatMap(p=>(p.interactions||p.interactionRecords||[]).map(i=>({portfolioId:p.portfolioId,interactionId:i.interactionId,ecmIds:(i.ecmIds||[]).join("; "),interactionType:i.interactionType,confirmed:i.confirmed,affectedUtilityType:i.affectedUtilityType,affectedEndUse:i.affectedEndUse,method:i.method,originalBaseline:i.trace?.originalBaseline??i.adjustment?.baselineEnergy,combinedSavings:i.trace?.combinedSavings,finalProposedEnergy:i.trace?.finalProposedEnergy,assumptions:(i.assumptions||[]).join("; "),warnings:(i.warnings||[]).join("; "),engineerNotes:i.engineerNotes})));
 return {"tables/systems.csv":csv(systemsHeaders,systems),"tables/equipment.csv":csv(equipmentHeaders,equipment),"tables/measurements.csv":csv(measurementHeaders,measurements),"tables/utilities.csv":csv(utilityHeaders,utilities),"tables/end_uses.csv":csv(endUseHeaders,endUses),"tables/ecms.csv":csv(ecmHeaders,ecms),"tables/calculations.csv":csv(calculationHeaders,calculations),"tables/ecm_portfolios.csv":csv(portfolioHeaders,portfolios),"tables/ecm_interactions.csv":csv(interactionHeaders,interactions)};
}
function dataUrlBlob(dataUrl){const match=/^data:([^;,]+)?(;base64)?,(.*)$/s.exec(dataUrl||"");if(!match)throw new Error("Invalid legacy data URL");const bytes=match[2]?Uint8Array.from(atob(match[3]),c=>c.charCodeAt(0)):enc.encode(decodeURIComponent(match[3]));return new Blob([bytes],{type:match[1]||"application/octet-stream"});}
function extension(type,name=""){const known={"image/jpeg":"jpg","image/png":"png","image/webp":"webp","image/heic":"heic","image/heif":"heif"};return known[String(type||"").toLowerCase()]||(/\.([a-z0-9]{2,5})$/i.exec(name)?.[1]?.toLowerCase())||"jpg";}
function validateReferences(audit){const warnings=[],errors=[],systemIds=new Set((audit.systems||[]).map(s=>s.systemRecordId)),equipmentIds=new Set((audit.equipment||[]).map(e=>e.recordId)),ecmIds=new Set((audit.ecms||[]).map(e=>e.ecmId)),calculationIds=new Set((audit.calculations||[]).map(c=>c.calculationId)),measurementIds=new Set();
 const accountIds=new Set(),billIds=new Set();(audit.utilityAccounts||[]).forEach(a=>{if(!a.utilityAccountId||accountIds.has(a.utilityAccountId))errors.push(`Missing or duplicate utility account ID ${a.utilityAccountId||"(blank)"}.`);accountIds.add(a.utilityAccountId);(a.bills||[]).forEach(b=>{if(!b.utilityBillId||billIds.has(b.utilityBillId))errors.push(`Missing or duplicate utility bill ID ${b.utilityBillId||"(blank)"}.`);billIds.add(b.utilityBillId);if(b.utilityAccountId!==a.utilityAccountId)errors.push(`Utility bill ${b.utilityBillId||"(unknown)"} has conflicting account relationship.`);});});
 const endUseIds=new Set();(audit.endUseModels||[]).forEach(m=>{if(!m.endUseModelId||endUseIds.has(m.endUseModelId))errors.push(`Missing or duplicate end-use model ID ${m.endUseModelId||"(blank)"}.`);endUseIds.add(m.endUseModelId);(m.systemRecordIds||[]).forEach(id=>{if(!systemIds.has(id))errors.push(`End-use model ${m.endUseModelId} references missing system ${id}.`);});(m.equipmentRecordIds||[]).forEach(id=>{if(!equipmentIds.has(id))errors.push(`End-use model ${m.endUseModelId} references missing equipment ${id}.`);});(m.calculationIds||[]).forEach(id=>{if(!calculationIds.has(id))errors.push(`End-use model ${m.endUseModelId} references missing calculation ${id}.`);});});
 const portfolioIds=new Set();(audit.ecmPortfolios||[]).forEach(p=>{if(!p.portfolioId||portfolioIds.has(p.portfolioId))errors.push(`Missing or duplicate portfolio ID ${p.portfolioId||"(blank)"}.`);portfolioIds.add(p.portfolioId);(p.ecmIds||[]).forEach(id=>{if(!ecmIds.has(id))errors.push(`Portfolio ${p.portfolioId} references missing ECM ${id}.`);});(p.sequence||[]).forEach(id=>{if(!(p.ecmIds||[]).includes(id))errors.push(`Portfolio ${p.portfolioId} sequence references excluded ECM ${id}.`);});(p.interactionRecords||[]).forEach(i=>(i.ecmIds||[]).forEach(id=>{if(!(p.ecmIds||[]).includes(id))errors.push(`Portfolio interaction ${i.interactionId} references ECM ${id} outside its portfolio.`);}));});
 (audit.equipment||[]).forEach(e=>{if(e.systemRecordId&&!systemIds.has(e.systemRecordId))errors.push(`Equipment ${e.equipmentId||e.recordId} references missing system ${e.systemRecordId}.`);(e.measurements||[]).forEach(m=>{if(measurementIds.has(m.measurementId))errors.push(`Duplicate measurement UUID ${m.measurementId}.`);measurementIds.add(m.measurementId);if(m.equipmentRecordId&&m.equipmentRecordId!==e.recordId)errors.push(`Measurement ${m.measurementId} has conflicting equipment relationship.`);});(e.photos||[]).forEach(p=>{if(p.equipmentRecordId&&p.equipmentRecordId!==e.recordId)errors.push(`Photo ${p.photoId} has conflicting equipment relationship.`);});});
 (audit.ecms||[]).forEach(e=>{(e.affectedEquipmentRecordIds||[]).forEach(id=>{if(!equipmentIds.has(id))errors.push(`ECM ${e.ecmId} references missing equipment ${id}.`);});(e.unresolvedEquipmentReferences||[]).filter(r=>!r.resolution).forEach(r=>warnings.push(`ECM ${e.ecmId} retains unresolved legacy equipment reference ${r.displayId}.`));});
 (audit.calculations||[]).forEach(c=>{if(!ecmIds.has(c.ecmId))errors.push(`Calculation ${c.calculationId} references missing ECM ${c.ecmId}.`);(c.equipmentRecordIds||[]).forEach(id=>{if(!equipmentIds.has(id))errors.push(`Calculation ${c.calculationId} references missing equipment ${id}.`);});(c.dependencyCalculationIds||[]).forEach(id=>{if(!calculationIds.has(id))errors.push(`Calculation ${c.calculationId} references missing dependency ${id}.`);});(c.inputs||[]).forEach(i=>{if(!i.sourceRecordId)return;const found=equipmentIds.has(i.sourceRecordId)||measurementIds.has(i.sourceRecordId)||calculationIds.has(i.sourceRecordId)||i.sourceRecordId===audit.auditId;if(!found)warnings.push(`Calculation ${c.calculationId} source ${i.sourceRecordId} cannot be resolved.`);});});return {warnings:[...new Set(warnings)],errors:[...new Set(errors)]};
}
function photoRecords(audit){const out=[];(audit.equipment||[]).forEach(e=>(e.photos||[]).forEach(p=>out.push({equipment:e,photo:p})));return out;}
async function prepare(audit,storedPhotos=[],readiness=[],progress=()=>{}){
 const sourceBefore=JSON.stringify(audit),copy=structuredClone(audit),storedById=new Map(storedPhotos.map(p=>[p.photoId,p])),usedStored=new Set(),paths=new Set(),files=[],photoWarnings=[],photoErrors=[],refs=photoRecords(copy);let done=0;
 if(!copy.endUseAnalysis&&END_USE_ANALYSIS)copy.endUseAnalysis=END_USE_ANALYSIS.analyze(copy);
 if(!copy.portfolioAnalysis&&PORTFOLIO_ANALYSIS)copy.portfolioAnalysis=PORTFOLIO_ANALYSIS.analyze(copy);
 progress({stage:"validating",done,total:refs.length});
 for(const {equipment,photo} of refs){
  let blob=null;const stored=storedById.get(photo.photoId);
  try{if(stored?.blob){blob=stored.blob;usedStored.add(photo.photoId);}else if(photo.dataUrl)blob=dataUrlBlob(photo.dataUrl);else throw new Error("no stored Blob or readable legacy image");}
  catch(error){photoErrors.push(`Missing photo ${photo.photoId} — ${equipment.equipmentId||equipment.recordId} ${photo.category||"Photo"}: ${error.message}`);done++;progress({stage:"photos",done,total:refs.length});continue;}
  const system=safeName(equipment.systemType,"Other"),eq=safeName(equipment.equipmentId,equipment.recordId),category=safeName(photo.category,"Photo"),ext=extension(blob.type,photo.name),base=`photos/${system}/${eq}/${eq}_${category}_${String(done+1).padStart(2,"0")}`;let path=`${base}.${ext}`,suffix=1;
  while(paths.has(path))path=`${base}_${safeName(photo.photoId,String(++suffix)).slice(-12)}.${ext}`;
  paths.add(path);photo.equipmentRecordId=equipment.recordId;photo.packagePath=path;photo.generatedFilename=path.split("/").pop();photo.exportedMimeType=blob.type||"application/octet-stream";files.push({path,blob});done++;progress({stage:"photos",done,total:refs.length});
 }
 storedPhotos.filter(p=>!usedStored.has(p.photoId)).forEach(p=>photoWarnings.push(`Orphan photo Blob ${p.photoId} is not referenced by audit metadata.`));
 const refIntegrity=validateReferences(copy),utilityBills=(copy.utilityAccounts||[]).reduce((n,a)=>n+(a.bills||[]).length,0)||(copy.utility?.months||[]).length,counts={systems:(copy.systems||[]).length,equipment:(copy.equipment||[]).length,measurements:(copy.equipment||[]).reduce((n,e)=>n+(e.measurements||[]).length,0),utilityAccounts:(copy.utilityAccounts||[]).length,utilityBills,utilityMonths:utilityBills,endUseModels:(copy.endUseAnalysis?.models||copy.endUseModels||[]).length,ecms:(copy.ecms||[]).length,calculations:(copy.calculations||[]).length,ecmPortfolios:(copy.ecmPortfolios||[]).length,ecmInteractions:(copy.ecmPortfolios||[]).reduce((n,p)=>n+(p.interactionRecords||[]).length,0),weatherDatasets:(copy.weatherDatasets||[]).length,manufacturerPerformanceDatasets:(copy.manufacturerPerformanceDatasets||[]).length,rcxContainers:(copy.rcxContainers||[]).length,photosReferenced:refs.length,photosExported:files.length},errors=[...refIntegrity.errors,...photoErrors],warnings=[...refIntegrity.warnings,...photoWarnings],status=errors.length?"FAIL":warnings.length?"PASS_WITH_WARNINGS":"PASS";
 copy.appVersion="5.3";copy.engineeringAnalysis=readiness;
 const manifest={packageFormatVersion:PACKAGE_FORMAT_VERSION,auditId:copy.auditId,facilityName:copy.site?.facilityName||"",auditDate:copy.site?.auditDate||"",exportGeneratedAt:new Date().toISOString(),appVersion:"5.3",schemaVersion:copy.schemaVersion,counts,utilityAnalysisSummary:copy.utilityAnalysis?{version:copy.utilityAnalysis.version,totals:copy.utilityAnalysis.totals,qaFlags:copy.utilityAnalysis.qaFlags,limitations:copy.utilityAnalysis.limitations}:null,endUseReconciliationSummary:copy.endUseAnalysis?{version:copy.endUseAnalysis.version,status:copy.endUseAnalysis.status,reconciliations:copy.endUseAnalysis.reconciliations,coverage:copy.endUseAnalysis.coverage,qaFlags:copy.endUseAnalysis.qaFlags,limitations:copy.endUseAnalysis.limitations}:null,portfolioAnalysisSummary:copy.portfolioAnalysis?{version:copy.portfolioAnalysis.version,portfolios:copy.portfolioAnalysis.portfolios.map(p=>({portfolioId:p.portfolioId,name:p.name,status:p.status,standaloneSavings:p.standaloneSavings,combinedSavings:p.combinedSavings,combinedCostSavings:p.combinedCostSavings,combinedImplementationCost:p.combinedImplementationCost,simplePaybackYears:p.simplePaybackYears,evidenceLevel:p.evidenceLevel,maturity:p.maturity,qaFlags:p.qaFlags})),limitations:copy.portfolioAnalysis.limitations}:null,advancedAnalysisSummary:{weatherDatasets:counts.weatherDatasets,manufacturerPerformanceDatasets:counts.manufacturerPerformanceDatasets,rcxContainers:counts.rcxContainers},integrity:{status,warnings,errors}},tableFiles=tables(copy,readiness);
 files.unshift({path:"audit.json",blob:new Blob([JSON.stringify(copy,null,2)],{type:"application/json"})},{path:"manifest.json",blob:new Blob([JSON.stringify(manifest,null,2)],{type:"application/json"})},...Object.entries(tableFiles).map(([path,text])=>({path,blob:new Blob([text],{type:"text/csv;charset=utf-8"})})));
 if(JSON.stringify(audit)!==sourceBefore)throw new Error("Export attempted to mutate the source audit.");return {files,manifest,audit:copy};
}
let crcTable=null;function crc32(bytes){if(!crcTable){crcTable=Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;return c>>>0;});}let c=0xffffffff;for(const b of bytes)c=crcTable[(c^b)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
function u16(view,o,v){view.setUint16(o,v,true);}function u32(view,o,v){view.setUint32(o,v>>>0,true);}function dosDate(date=new Date()){const y=Math.max(1980,date.getFullYear());return {time:(date.getHours()<<11)|(date.getMinutes()<<5)|(date.getSeconds()>>1),date:((y-1980)<<9)|((date.getMonth()+1)<<5)|date.getDate()};}
async function zip(files,progress=()=>{}){const parts=[],central=[];let offset=0,index=0;for(const file of files){const name=enc.encode(file.path),blob=file.blob instanceof Blob?file.blob:new Blob([file.blob]),bytes=new Uint8Array(await blob.arrayBuffer()),crc=crc32(bytes),dt=dosDate(),header=new Uint8Array(30+name.length),v=new DataView(header.buffer);u32(v,0,0x04034b50);u16(v,4,20);u16(v,6,0x0800);u16(v,8,0);u16(v,10,dt.time);u16(v,12,dt.date);u32(v,14,crc);u32(v,18,blob.size);u32(v,22,blob.size);u16(v,26,name.length);header.set(name,30);parts.push(header,blob);central.push({name,crc,size:blob.size,offset,dt});offset+=header.length+blob.size;bytes.fill(0);index++;progress({stage:"zipping",done:index,total:files.length});}const centralStart=offset;for(const f of central){const h=new Uint8Array(46+f.name.length),v=new DataView(h.buffer);u32(v,0,0x02014b50);u16(v,4,20);u16(v,6,20);u16(v,8,0x0800);u16(v,10,0);u16(v,12,f.dt.time);u16(v,14,f.dt.date);u32(v,16,f.crc);u32(v,20,f.size);u32(v,24,f.size);u16(v,28,f.name.length);u32(v,42,f.offset);h.set(f.name,46);parts.push(h);offset+=h.length;}const end=new Uint8Array(22),v=new DataView(end.buffer);u32(v,0,0x06054b50);u16(v,8,central.length);u16(v,10,central.length);u32(v,12,offset-centralStart);u32(v,16,centralStart);parts.push(end);return new Blob(parts,{type:"application/zip"});}
async function verifyZip(blob,expectedCount){if(blob.size<22)return false;const bytes=new Uint8Array(await blob.slice(-22).arrayBuffer()),view=new DataView(bytes.buffer);return view.getUint32(0,true)===0x06054b50&&view.getUint16(8,true)===expectedCount&&view.getUint16(10,true)===expectedCount;}
async function build(audit,storedPhotos=[],readiness=[],progress=()=>{}){const prepared=await prepare(audit,storedPhotos,readiness,progress),blob=await zip(prepared.files,progress);progress({stage:"complete",done:prepared.files.length,total:prepared.files.length});if(!await verifyZip(blob,prepared.files.length))throw new Error("ZIP verification failed; no package was offered for saving.");return {...prepared,blob,fileName:`${safeName(audit.site?.facilityName,"Facility")}_${safeName(audit.site?.auditDate||new Date().toISOString().slice(0,10),"date")}_Audist.zip`};}
return {PACKAGE_FORMAT_VERSION,safeName,csv,tables,dataUrlBlob,validateReferences,prepare,zip,verifyZip,build};
});
