(function(root,factory){const deps=typeof module!=="undefined"&&module.exports?{utility:require("./utility-analysis.js"),endUse:require("./end-use-analysis.js"),portfolio:require("./portfolio-analysis.js"),workflow:require("./workflow.js"),calculations:require("./calculations.js")}:{utility:root.AudistUtilityAnalysis,endUse:root.AudistEndUseAnalysis,portfolio:root.AudistPortfolioAnalysis,workflow:root.AudistWorkflow,calculations:root.AudistCalculations};const api=factory(deps);if(typeof module!=="undefined"&&module.exports)module.exports=api;root.AudistQaRules=api;})(typeof globalThis!=="undefined"?globalThis:this,function(D){
"use strict";
const VERSION="1.0",SEVERITIES=["BLOCKER","HIGH","MEDIUM","LOW","INFO"],CATEGORIES=["DATA_INTEGRITY","FIELD_COMPLETENESS","MEASUREMENT_QA","PHOTO_EVIDENCE","UTILITY_QA","CALCULATION_QA","END_USE_RECONCILIATION","ECM_QA","PORTFOLIO_QA","PROVENANCE_QA","ECONOMICS_QA","EXPORT_QA","REPORT_READINESS"],STATES=["OPEN","REVIEWED","ACCEPTED_LIMITATION","RESOLVED","NOT_APPLICABLE"],openStates=new Set(["OPEN","REVIEWED"]),has=v=>v!==undefined&&v!==null&&v!=="",num=v=>Number(v),finite=v=>Number.isFinite(num(v));
function stable(value){let h=2166136261;for(const c of String(value)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return (h>>>0).toString(36);}
function finding(rule,recordType,ids,title,description,action,evidence=[]){const affectedRecordIds=[...new Set((ids||[]).filter(Boolean).map(String))].sort(),findingId=`${rule.ruleId}-${stable([recordType,...affectedRecordIds,title].join("|"))}`;return {findingId,ruleId:rule.ruleId,ruleVersion:rule.version,category:rule.category,severity:rule.severity,status:"OPEN",title,description,affectedRecordType:recordType,affectedRecordIds,evidence,recommendedAction:action};}
const RULES=[];function rule(ruleId,category,severity,evaluator){const r={ruleId,version:"1.0",category,severity,evaluator};RULES.push(r);return r;}
function duplicateRules(audit,r,key,type,label){const seen=new Set(),out=[];(audit[key]||[]).forEach(x=>{const id=x[r];if(!has(id)||seen.has(id))out.push(finding(this,type,[id],`Missing or duplicate ${label}`,`${label} values must be present and unique.`,`Restore a unique stable ${label}.`,[{field:r,value:id??null}]));seen.add(id);});return out;}
rule("QA-DATA-001","DATA_INTEGRITY","BLOCKER",function(a){return duplicateRules.call(this,a,"recordId","equipment","equipment","equipment UUID");});
rule("QA-DATA-002","DATA_INTEGRITY","BLOCKER",function(a){return duplicateRules.call(this,a,"systemRecordId","systems","system","system UUID");});
rule("QA-DATA-003","DATA_INTEGRITY","BLOCKER",function(a){return duplicateRules.call(this,a,"ecmId","ecms","ecm","ECM ID");});
rule("QA-DATA-004","DATA_INTEGRITY","BLOCKER",function(a){return duplicateRules.call(this,a,"calculationId","calculations","calculation","calculation ID");});
rule("QA-DATA-005","DATA_INTEGRITY","BLOCKER",function(a){const ids=new Set((a.systems||[]).map(x=>x.systemRecordId));return (a.equipment||[]).filter(x=>x.systemRecordId&&!ids.has(x.systemRecordId)).map(x=>finding(this,"equipment",[x.recordId,x.systemRecordId],"Equipment references missing system",`${x.equipmentId||x.recordId} references system ${x.systemRecordId}.`,"Restore the system relationship or explicitly reassign the equipment."));});
rule("QA-DATA-006","DATA_INTEGRITY","HIGH",function(a){const ids=new Set((a.equipment||[]).map(x=>x.recordId)),out=[];(a.equipment||[]).forEach(eq=>(eq.measurements||[]).forEach(m=>{if(m.equipmentRecordId&&m.equipmentRecordId!==eq.recordId)out.push(finding(this,"measurement",[m.measurementId,eq.recordId],"Measurement relationship is inconsistent",`Measurement ${m.measurementId} points to a different equipment UUID.`,"Restore the authoritative equipment relationship."));}));(a.ecms||[]).forEach(e=>(e.affectedEquipmentRecordIds||[]).filter(id=>!ids.has(id)).forEach(id=>out.push(finding(this,"ecm",[e.ecmId,id],"ECM references missing equipment",`${e.ecmId} references missing equipment ${id}.`,"Resolve or remove the broken relationship without inventing equipment."))));return out;});
rule("QA-DATA-007","DATA_INTEGRITY","HIGH",function(a){const ecm=new Set((a.ecms||[]).map(x=>x.ecmId)),calc=new Set((a.calculations||[]).map(x=>x.calculationId)),out=[];(a.calculations||[]).forEach(c=>{if(!ecm.has(c.ecmId))out.push(finding(this,"calculation",[c.calculationId,c.ecmId],"Calculation references missing ECM",`${c.calculationId} references missing ECM ${c.ecmId}.`,"Restore the ECM or repair the calculation relationship."));(c.dependencyCalculationIds||[]).filter(id=>!calc.has(id)).forEach(id=>out.push(finding(this,"calculation",[c.calculationId,id],"Calculation dependency is missing",`${c.calculationId} depends on missing calculation ${id}.`,"Restore or explicitly replace the dependency, then recalculate.")));});return out;});
rule("QA-DATA-008","DATA_INTEGRITY","HIGH",function(a){return (a.ecms||[]).filter(e=>(e.unresolvedEquipmentReferences||[]).some(x=>!x.resolution)).map(e=>finding(this,"ecm",[e.ecmId],"Legacy equipment relationship remains unresolved",`${e.ecmId} retains one or more unresolved migration references.`,"Review and explicitly resolve each legacy equipment reference.",(e.unresolvedEquipmentReferences||[]).map(x=>({displayId:x.displayId,source:x.source}))));});
rule("QA-DATA-009","DATA_INTEGRITY","BLOCKER",function(a){return num(a.schemaVersion)>4?[finding(this,"audit",[a.auditId],"Audit schema is newer than this QA engine",`Schema ${a.schemaVersion} cannot be safely reviewed by schema-4 QA rules.`,"Open the audit with a compatible Audist version.")]:[];});
rule("QA-DATA-010","DATA_INTEGRITY","MEDIUM",function(a,c){const refs=new Set((a.equipment||[]).flatMap(e=>(e.photos||[]).map(p=>p.photoId)));return (c.storedPhotos||[]).filter(p=>p.photoId&&!refs.has(p.photoId)).map(p=>finding(this,"photo",[p.photoId],"Orphan photo Blob is not referenced",`Stored photo ${p.photoId} is not referenced by audit metadata.`,"Review and recover the photo relationship before permanent cleanup."));});
rule("QA-DATA-011","DATA_INTEGRITY","HIGH",function(a){return (a.equipment||[]).flatMap(eq=>(eq.photos||[]).filter(p=>p.equipmentRecordId&&p.equipmentRecordId!==eq.recordId).map(p=>finding(this,"photo",[p.photoId,eq.recordId],"Photo relationship is inconsistent",`Photo ${p.photoId} points to a different equipment UUID.`,"Restore the authoritative equipment relationship.")));});
rule("QA-FIELD-001","FIELD_COMPLETENESS","HIGH",function(a){if(a.qaDeclarations?.fieldScopeReviewed)return [];return [finding(this,"audit",[a.auditId],"Field scope has not been explicitly reviewed","The audit does not record completion of the field-scope review.","Complete the Before Leaving Site review and confirm field scope.")];});
rule("QA-FIELD-002","FIELD_COMPLETENESS","HIGH",function(a){const equipment=(a.equipment||[]);return (a.systems||[]).filter(s=>String(s.status).toLowerCase()==="present"&&!equipment.some(e=>e.systemRecordId===s.systemRecordId)).map(s=>finding(this,"system",[s.systemRecordId],"Present system has no equipment records",`${s.name||s.systemId||s.systemType} is marked Present but has no equipment.`,"Document the equipment or revise the system scope with an explicit basis."));});
rule("QA-FIELD-003","FIELD_COMPLETENESS","MEDIUM",function(a){return (a.equipment||[]).filter(e=>!has(e.equipmentId)||!has(e.systemType)).map(e=>finding(this,"equipment",[e.recordId],"Equipment identity is incomplete",`${e.equipmentId||e.recordId} lacks a display ID or system type.`,"Complete the equipment core identity fields."));});
rule("QA-FIELD-004","FIELD_COMPLETENESS","HIGH",function(a){if(!D.workflow||!D.calculations)return [];return (a.ecms||[]).flatMap(e=>{const r=D.workflow.engineeringReadiness(a,e,D.calculations);return r.missingFieldInputs.length?[finding(this,"ecm",[e.ecmId],"Active ECM is missing onsite evidence",`${e.ecmId} is missing: ${r.missingFieldInputs.join(", ")}.`,"Collect the FIELD_REQUIRED evidence or document why the ECM is out of scope.",r.missingFieldInputs.map(x=>({missing:x})))]:[];});});
rule("QA-MEAS-001","MEASUREMENT_QA","HIGH",function(a){const seen=new Set(),out=[];(a.equipment||[]).forEach(eq=>(eq.measurements||[]).forEach(m=>{if(!has(m.measurementId)||seen.has(m.measurementId))out.push(finding(this,"measurement",[m.measurementId,eq.recordId],"Missing or duplicate measurement ID","Measurement IDs must be present and unique.","Assign a unique stable measurement ID."));seen.add(m.measurementId);}));return out;});
rule("QA-MEAS-002","MEASUREMENT_QA","MEDIUM",function(a){return (a.equipment||[]).flatMap(eq=>(eq.measurements||[]).filter(m=>!has(m.unit)).map(m=>finding(this,"measurement",[m.measurementId],"Measurement unit is missing",`${m.parameter||"Measurement"} has no unit.`,"Enter the unit without changing the recorded value.")));});
rule("QA-MEAS-003","MEASUREMENT_QA","MEDIUM",function(a){return (a.equipment||[]).flatMap(eq=>(eq.measurements||[]).filter(m=>!has(m.provenance)&&!has(m.source)).map(m=>finding(this,"measurement",[m.measurementId],"Measurement provenance is missing",`${m.parameter||"Measurement"} has no provenance.`,"Identify whether the value is Measured, Calculated, Estimated, or Assumed.")));});
rule("QA-MEAS-004","MEASUREMENT_QA","HIGH",function(a){return (a.equipment||[]).flatMap(eq=>(eq.measurements||[]).filter(m=>/hour|runtime/i.test(m.parameter||"")&&finite(m.value)&&num(m.value)>8760).map(m=>finding(this,"measurement",[m.measurementId],"Runtime exceeds 8,760 hours",`${m.parameter} is ${m.value} ${m.unit||""}.`,"Correct the value/unit or document a non-annual boundary.")));});
rule("QA-MEAS-005","MEASUREMENT_QA","HIGH",function(a){return (a.equipment||[]).flatMap(eq=>(eq.measurements||[]).filter(m=>/(efficiency|cop|eer)/i.test(m.parameter||"")&&finite(m.value)&&num(m.value)<=0).map(m=>finding(this,"measurement",[m.measurementId],"Efficiency is not physically valid",`${m.parameter} is ${m.value}.`,"Verify the metric, value, and unit.")));});
rule("QA-MEAS-006","PROVENANCE_QA","HIGH",function(a){return (a.equipment||[]).flatMap(eq=>(eq.measurements||[]).filter(m=>String(m.provenance||m.source)==="Measured"&&/calculat/i.test(`${m.parameter||""} ${m.method||""}`)).map(m=>finding(this,"measurement",[m.measurementId],"Calculated value is labeled Measured",`${m.parameter} is labeled Measured but its parameter or method indicates calculation.`,"Correct the provenance; do not alter the value automatically.")));});
rule("QA-MEAS-007","MEASUREMENT_QA","MEDIUM",function(a){return (a.equipment||[]).flatMap(eq=>(eq.measurements||[]).filter(m=>has(m.value)&&!finite(m.numericValue??m.value)&&/(power|kw|watt|flow|pressure|temperature|runtime|hour|efficiency|cop|eer|capacity|light|lux|foot.?candle)/i.test(m.parameter||"")).map(m=>finding(this,"measurement",[m.measurementId],"Numeric measurement is not numeric",`${m.parameter} has value ${m.value}.`,"Verify the recorded value without guessing a replacement.")));});
rule("QA-MEAS-008","MEASUREMENT_QA","HIGH",function(a){return (a.equipment||[]).flatMap(eq=>(eq.measurements||[]).filter(m=>finite(m.numericValue??m.value)&&num(m.numericValue??m.value)<0&&/(power|kw|watt|flow|pressure|runtime|hour|efficiency|cop|eer|capacity|light|lux|foot.?candle)/i.test(m.parameter||"")).map(m=>finding(this,"measurement",[m.measurementId],"Measurement is physically invalid for this parameter",`${m.parameter} is negative (${m.numericValue??m.value} ${m.unit||""}).`,"Verify sign, parameter, and unit; preserve the original evidence until reviewed.")));});
rule("QA-MEAS-009","MEASUREMENT_QA","MEDIUM",function(a){return (a.equipment||[]).flatMap(eq=>(eq.measurements||[]).filter(m=>finite(m.numericValue??m.value)&&/(efficiency|percent|percentage)/i.test(m.parameter||"")&&((/%/.test(m.unit||"")&&num(m.numericValue??m.value)>0&&num(m.numericValue??m.value)<1)||(/fraction|decimal/i.test(m.unit||"")&&num(m.numericValue??m.value)>1))).map(m=>finding(this,"measurement",[m.measurementId],"Percent-versus-decimal representation is ambiguous",`${m.parameter} is ${m.numericValue??m.value} ${m.unit||""}.`,"Confirm whether the value is a fraction or percent; do not rescale automatically.")));});
rule("QA-MEAS-010","MEASUREMENT_QA","MEDIUM",function(a){return (a.equipment||[]).flatMap(eq=>(eq.measurements||[]).filter(m=>/(light level|illuminance|lux|foot.?candle)/i.test(m.parameter||"")&&!/(lux|fc|foot.?candle)/i.test(m.unit||"")).map(m=>finding(this,"measurement",[m.measurementId],"Light-level unit is missing or unexpected",`${m.parameter} uses unit ${m.unit||"(missing)"}.`,"Record lux or foot-candles and retain the measurement method.")));});
rule("QA-MEAS-011","MEASUREMENT_QA","MEDIUM",function(a){return (a.equipment||[]).flatMap(eq=>(eq.measurements||[]).filter(m=>/(flow|pressure)/i.test(m.parameter||"")&&!has(m.unit)).map(m=>finding(this,"measurement",[m.measurementId],"Flow or pressure lacks a unit",`${m.parameter} cannot be interpreted without a unit.`,"Record the observed unit and measurement context.")));});
rule("QA-MEAS-012","MEASUREMENT_QA","LOW",function(a){return (a.equipment||[]).flatMap(eq=>(eq.measurements||[]).filter(m=>/temperature/i.test(m.parameter||"")&&String(m.provenance||m.source)==="Measured"&&!has(m.method)&&!has(m.instrument)).map(m=>finding(this,"measurement",[m.measurementId],"Measured temperature lacks method or instrument",`${m.parameter} is Measured without method/instrument documentation.`,"Document the instrument or measurement method where available.")));});
rule("QA-MEAS-013","MEASUREMENT_QA","HIGH",function(a){const out=[];(a.equipment||[]).forEach(eq=>{const groups=new Map();(eq.measurements||[]).filter(m=>finite(m.numericValue??m.value)).forEach(m=>{const k=String(m.parameter||"").trim().toLowerCase();if(k){const list=groups.get(k)||[];list.push(m);groups.set(k,list);}});for(const [parameter,list] of groups)if(list.length>1&&new Set(list.map(m=>`${num(m.numericValue??m.value)}|${String(m.unit||"").toLowerCase()}`)).size>1)out.push(finding(this,"measurement",list.map(m=>m.measurementId),"Conflicting duplicate measurements",`${parameter} has multiple different recorded values for ${eq.equipmentId||eq.recordId}.`,"Select the applicable evidence explicitly; do not average automatically."));});return out;});
rule("QA-PHOTO-001","PHOTO_EVIDENCE","HIGH",function(a,c){const stored=new Set((c.storedPhotos||[]).map(p=>p.photoId));return (a.equipment||[]).flatMap(eq=>(eq.photos||[]).filter(p=>!p.dataUrl&&!stored.has(p.photoId)).map(p=>finding(this,"photo",[p.photoId,eq.recordId],"Referenced photo payload is missing",`${p.category||"Photo"} metadata exists but no Blob or legacy payload is available.`,"Recover or recapture the evidence photo.")));});
rule("QA-PHOTO-002","PHOTO_EVIDENCE","MEDIUM",function(a){const seen=new Set(),out=[];(a.equipment||[]).forEach(eq=>(eq.photos||[]).forEach(p=>{if(!has(p.photoId)||seen.has(p.photoId))out.push(finding(this,"photo",[p.photoId,eq.recordId],"Missing or duplicate photo metadata ID","Photo metadata IDs must be present and unique.","Repair the photo metadata relationship."));seen.add(p.photoId);}));return out;});
rule("QA-UTIL-001","UTILITY_QA","MEDIUM",function(a){if(a.qaDeclarations?.utilityAnalysisNotRequired)return [];const analysis=D.utility?.analyze(a),accounts=analysis?.accountResults||[];return accounts.length&&!accounts.every(x=>/^COMPLETE_/.test(x.completeness?.status||""))?[finding(this,"utility",accounts.map(x=>x.utilityAccountId),"Utility baseline is incomplete","One or more utility accounts do not form a complete annual baseline.","Complete billing coverage or explicitly accept the limitation.",accounts.map(x=>({accountId:x.utilityAccountId,status:x.completeness?.status})))]:[];});
rule("QA-UTIL-002","UTILITY_QA","HIGH",function(a){const qa=D.utility?.analyze(a)?.qaFlags||[];return qa.filter(q=>/DUPLICATE|OVERLAP|NEGATIVE|INVALID/.test(q.code||"")).map(q=>finding(this,"utility",q.recordIds||[a.auditId],q.code.replaceAll("_"," "),q.message||q.code,"Review the source bills; do not silently repair them.",[q]));});
rule("QA-UTIL-003","UTILITY_QA","MEDIUM",function(a){const results=D.utility?.analyze(a)?.accountResults||[];return results.flatMap(r=>(r.completeness?.flags||[]).filter(q=>!/DUPLICATE|OVERLAP|NEGATIVE|INVALID/.test(q.code||"")).map(q=>finding(this,"utility",[r.utilityAccountId,q.billId],q.code.replaceAll("_"," "),`${r.utilityAccountId}: ${q.code.replaceAll("_"," ")}.`,"Review billing coverage, dates, units, and represented analysis boundary.",[q])));});
rule("QA-UTIL-004","UTILITY_QA","HIGH",function(a){const flags=D.utility?.analyze(a)?.qaFlags||[];return flags.filter(q=>/EXCEEDS_BASELINE|EXCEEDS_OBSERVED_PEAK/.test(q.code||"")).map(q=>finding(this,"audit",[a.auditId,q.calculationId],q.code.replaceAll("_"," "),"Claimed savings exceed the applicable observed facility boundary.","Review calculation and utility boundaries; do not cap or scale savings automatically.",[q]));});
rule("QA-UTIL-005","UTILITY_QA","MEDIUM",function(a){const flags=D.utility?.analyze(a)?.qaFlags||[];return flags.filter(q=>/EUI_REQUIRES|RATE_CONFLICT/.test(q.code||"")).map(q=>finding(this,"audit",[a.auditId,q.code],q.code.replaceAll("_"," "),"Utility-derived metric or rate basis requires review.","Complete the source basis or explicitly select the applicable rate.",[q]));});
rule("QA-CALC-001","CALCULATION_QA","HIGH",function(a){return (a.calculations||[]).filter(c=>c.status==="Needs Recalculation").map(c=>finding(this,"calculation",[c.calculationId],"Calculation is stale",`${c.calculationId} requires recalculation because source evidence changed.`,"Review changed inputs and explicitly recalculate."));});
rule("QA-CALC-002","CALCULATION_QA","BLOCKER",function(a){return (a.calculations||[]).filter(c=>!has(c.methodId)||!has(c.methodVersion)||!Array.isArray(c.inputs)||!Array.isArray(c.outputs)).map(c=>finding(this,"calculation",[c.calculationId],"Calculation record is structurally incomplete","Method/version/input/output snapshots are required for reproducibility.","Restore a complete calculation record or recreate it from supported evidence."));});
rule("QA-CALC-003","PROVENANCE_QA","HIGH",function(a){return (a.calculations||[]).flatMap(c=>(c.inputs||[]).filter(i=>!has(i.provenance)||!has(i.sourceDescription)).map(i=>finding(this,"calculation",[c.calculationId,i.parameterId],"Calculation input is not traceable",`${c.calculationId} input ${i.displayName||i.parameterId} lacks provenance or source description.`,"Document the source and provenance, then recalculate.")));});
rule("QA-CALC-004","CALCULATION_QA","HIGH",function(a){return (a.calculations||[]).filter(c=>c.evidenceLevel==="D"&&c.maturity!=="SCREENING").map(c=>finding(this,"calculation",[c.calculationId],"Evidence D calculation overstates maturity",`${c.calculationId} is Evidence D but is labeled ${c.maturity}.`,"Set the result maturity to SCREENING after engineering review."));});
rule("QA-CALC-005","CALCULATION_QA","MEDIUM",function(a){return (a.calculations||[]).flatMap(c=>(c.qaFlags||[]).map(q=>finding(this,"calculation",[c.calculationId,q.code],q.code.replaceAll("_"," "),q.message||q.code,"Review the method-specific QA evidence.",[q])));});
rule("QA-CALC-006","CALCULATION_QA","HIGH",function(a){return (a.calculations||[]).filter(c=>c.status&&!["Calculated","Needs Recalculation"].includes(c.status)).map(c=>finding(this,"calculation",[c.calculationId],"Calculation is not complete",`${c.calculationId} is ${c.status}.`,"Complete required evidence or retain the method as not ready without generating savings."));});
rule("QA-CALC-007","CALCULATION_QA","HIGH",function(a){return (a.calculations||[]).flatMap(c=>(c.inputs||[]).filter(i=>/default|deemed/i.test(`${i.provenance||""} ${i.sourceDescription||""}`)).map(i=>finding(this,"calculation",[c.calculationId,i.parameterId],"Calculation uses a default or deemed input",`${c.calculationId} input ${i.displayName||i.parameterId} uses a default/deemed basis.`,"Confirm the method explicitly permits this basis and document the governing source.")));});
rule("QA-PROV-001","PROVENANCE_QA","HIGH",function(a){const sources=new Map();(a.equipment||[]).forEach(eq=>{sources.set(eq.recordId,{provenance:"Field record"});(eq.measurements||[]).forEach(m=>sources.set(m.measurementId,m));});(a.calculations||[]).forEach(c=>sources.set(c.calculationId,{provenance:"Calculated"}));return (a.calculations||[]).flatMap(c=>(c.inputs||[]).filter(i=>i.sourceRecordId&&sources.has(i.sourceRecordId)&&String(i.provenance)==="Measured"&&/Assumed|Estimated|Calculated/i.test(String(sources.get(i.sourceRecordId).provenance||sources.get(i.sourceRecordId).source||""))).map(i=>finding(this,"calculation",[c.calculationId,i.parameterId,i.sourceRecordId],"Calculation input provenance contradicts its source",`${i.displayName||i.parameterId} is marked Measured but its source is ${sources.get(i.sourceRecordId).provenance||sources.get(i.sourceRecordId).source}.`,"Correct the provenance relationship without changing the source value.")));});
rule("QA-PROV-002","PROVENANCE_QA","MEDIUM",function(a){return (a.manufacturerPerformanceDatasets||[]).filter(d=>!has(d.manufacturer)||!has(d.sourceDocument)).map(d=>finding(this,"manufacturerPerformanceDataset",[d.performanceDatasetId],"Manufacturer performance evidence lacks source",`${d.performanceDatasetId||"Performance dataset"} lacks manufacturer or source-document identity.`,"Record the manufacturer and governing source document."));});
rule("QA-ENDUSE-001","END_USE_RECONCILIATION","HIGH",function(a){const x=D.endUse?.analyze(a);return Object.entries(x?.reconciliations||{}).filter(([,r])=>r.available&&r.absoluteGapPercent>20).map(([type,r])=>finding(this,"endUse",[type],"Material end-use reconciliation gap",`${type} modeled energy differs from utility baseline by ${r.absoluteGapPercent.toFixed(1)}%.`,"Review missing end uses, model boundaries, and evidence; do not force reconciliation.",[r]));});
rule("QA-ENDUSE-002","END_USE_RECONCILIATION","MEDIUM",function(a){const x=D.endUse?.analyze(a);return (x?.qaFlags||[]).map(q=>finding(this,"endUse",q.recordIds||[a.auditId],q.code.replaceAll("_"," "),q.message||q.code,"Review the modeled end-use evidence and relationships.",[q]));});
rule("QA-ECM-001","ECM_QA","HIGH",function(a){return (a.ecms||[]).filter(e=>{const savings=e.savings?.annualEnergySavings??e.annualEnergySavings??e.savings?.costSavings??e.costSavings;return finite(savings)&&num(savings)!==0&&!(e.calculationIds||[]).length;}).map(e=>finding(this,"ecm",[e.ecmId],"ECM claims savings without a calculation",`${e.ecmId} contains savings but no calculation relationship.`,"Attach a reproducible calculation or remove the unsupported savings claim."));});
rule("QA-ECM-002","ECM_QA","MEDIUM",function(a){return (a.ecms||[]).filter(e=>!has(e.existingCondition||e.existing)||!has(e.proposedImprovement||e.proposed)).map(e=>finding(this,"ecm",[e.ecmId],"ECM condition definition is incomplete",`${e.ecmId} lacks an existing or proposed condition.`,"Document both conditions before report drafting."));});
rule("QA-ECM-003","ECM_QA","HIGH",function(a){return (a.ecms||[]).filter(e=>!(e.affectedEquipmentRecordIds||[]).length&&((e.calculationIds||[]).length||finite(e.savings?.annualEnergySavings??e.annualEnergySavings))).map(e=>finding(this,"ecm",[e.ecmId],"Calculated ECM has no affected equipment",`${e.ecmId} has a calculation or savings claim without an equipment relationship.`,"Link the authoritative equipment UUID or document a valid whole-building boundary."));});
rule("QA-ECM-004","ECM_QA","MEDIUM",function(a){return (a.ecms||[]).filter(e=>finite(e.implementationCost)&&num(e.implementationCost)!==0&&!has(e.costBasis)&&!has(e.costSource)&&!has(e.costProvenance)&&!has(e.costNotes)).map(e=>finding(this,"ecm",[e.ecmId],"Implementation cost lacks provenance",`${e.ecmId} has an implementation cost without a source or basis.`,"Document the estimate, quote, allowance, or incentive basis."));});
rule("QA-ECM-005","ECM_QA","MEDIUM",function(a){const calc=new Map((a.calculations||[]).map(c=>[c.calculationId,c]));return (a.ecms||[]).filter(e=>(e.calculationIds||[]).some(id=>{const c=calc.get(id);return c&&c.status==="Calculated"&&!(c.assumptions||[]).length;})).map(e=>finding(this,"ecm",[e.ecmId],"Calculated ECM has no visible assumptions",`${e.ecmId} uses a calculated result with no assumption record.`,"Confirm that no assumptions apply or document them explicitly."));});
rule("QA-ECON-001","ECONOMICS_QA","MEDIUM",function(a){return (a.ecms||[]).filter(e=>finite(e.implementationCost)&&num(e.implementationCost)<0&&!has(e.costBasis||e.costNotes)).map(e=>finding(this,"ecm",[e.ecmId],"Negative implementation cost lacks explanation",`${e.ecmId} has implementation cost ${e.implementationCost}.`,"Document the rebate/credit/cost boundary or correct the cost."));});
rule("QA-ECON-002","ECONOMICS_QA","HIGH",function(a){return (a.ecms||[]).filter(e=>finite(e.simplePaybackYears)&&(!finite(e.implementationCost)||num(e.implementationCost)<0||!finite(e.costSavings??e.savings?.costSavings)||num(e.costSavings??e.savings?.costSavings)<=0)).map(e=>finding(this,"ecm",[e.ecmId],"Simple payback lacks valid cost and savings",`${e.ecmId} reports payback without positive annual cost savings and a valid implementation cost.`,"Review the economics inputs and recalculate."));});
rule("QA-ECON-003","ECONOMICS_QA","MEDIUM",function(a){return (a.ecms||[]).filter(e=>finite(e.npv)&&!finite(e.discountRate)&&!finite(e.economics?.discountRate)).map(e=>finding(this,"ecm",[e.ecmId],"NPV lacks a discount-rate basis",`${e.ecmId} reports NPV without a discount rate.`,"Document the discount rate and analysis period, then recalculate."));});
rule("QA-ECON-004","ECONOMICS_QA","MEDIUM",function(a){return (a.ecms||[]).filter(e=>finite(e.incentives)&&finite(e.implementationCost)&&num(e.incentives)>num(e.implementationCost)&&!has(e.costNotes)).map(e=>finding(this,"ecm",[e.ecmId],"Incentives exceed implementation cost",`${e.ecmId} incentives exceed implementation cost without explanation.`,"Confirm incentive and cost boundaries or document the valid exception."));});
rule("QA-PORT-001","PORTFOLIO_QA","HIGH",function(a){const result=D.portfolio?.analyze(a);return (result?.portfolios||[]).flatMap(p=>(p.qaFlags||[]).map(q=>finding(this,"portfolio",[p.portfolioId,q.code],q.code.replaceAll("_"," "),q.message||q.code,"Resolve the interaction or explicitly document an accepted limitation.",[q])));});
rule("QA-EXPORT-001","EXPORT_QA","HIGH",function(a,c){return c.exportIntegrity?.errors?.map((message,i)=>finding(this,"export",[a.auditId,String(i)],"Professional package integrity error",message,"Repair the referenced data or photo before relying on the export."))||[];});
rule("QA-REPORT-001","REPORT_READINESS","MEDIUM",function(a){return a.qaDeclarations?.analysisScopeReviewed?[]:[finding(this,"audit",[a.auditId],"Analysis scope has not been explicitly reviewed","The audit does not record completion of analysis-scope review.","Review utility, calculations, end uses, ECMs, and portfolios before report drafting.")];});
function applyStates(findings,states=[]){const map=new Map((states||[]).map(s=>[s.findingId,s]));return findings.map(f=>{const s=map.get(f.findingId);return s&&STATES.includes(s.status)?{...f,status:s.status,engineerNote:s.engineerNote||"",stateUpdatedAt:s.updatedAt||null}:f;});}
function readiness(findings){const unresolved=findings.filter(f=>openStates.has(f.status)),accepted=findings.filter(f=>f.status==="ACCEPTED_LIMITATION"),field=unresolved.some(f=>f.category==="FIELD_COMPLETENESS"&&["BLOCKER","HIGH"].includes(f.severity)),analysis=unresolved.some(f=>["UTILITY_QA","CALCULATION_QA","END_USE_RECONCILIATION","ECM_QA","PORTFOLIO_QA"].includes(f.category)&&["BLOCKER","HIGH","MEDIUM"].includes(f.severity)),high=unresolved.some(f=>["BLOCKER","HIGH"].includes(f.severity));if(field)return "FIELD_INCOMPLETE";if(analysis)return "ANALYSIS_INCOMPLETE";if(high)return "ENGINEERING_REVIEW_REQUIRED";if(accepted.length||unresolved.length)return "REPORT_READY_WITH_LIMITATIONS";return "REPORT_READY";}
function evaluate(audit,context={}){const before=JSON.stringify(audit),generatedAt=context.generatedAt||new Date().toISOString(),raw=RULES.flatMap(r=>r.evaluator(audit,context)||[]),unique=new Map();for(const f of raw){const prior=unique.get(f.findingId);if(prior)prior.evidence=[...prior.evidence,...f.evidence];else unique.set(f.findingId,f);}const findings=applyStates([...unique.values()],audit.qaFindingStates||[]).map(f=>({...f,generatedAt})),severitySummary=Object.fromEntries(SEVERITIES.map(s=>[s,findings.filter(f=>openStates.has(f.status)&&f.severity===s).length])),categorySummaries=CATEGORIES.map(category=>({category,unresolvedCount:findings.filter(f=>f.category===category&&openStates.has(f.status)).length,severitySummary:Object.fromEntries(SEVERITIES.map(s=>[s,findings.filter(f=>f.category===category&&f.severity===s&&openStates.has(f.status)).length]))})),result={version:VERSION,generatedAt,auditId:audit.auditId,status:readiness(findings),severitySummary,findings,categorySummaries,readiness:readiness(findings),unresolvedCount:findings.filter(f=>openStates.has(f.status)).length,acceptedLimitations:findings.filter(f=>f.status==="ACCEPTED_LIMITATION")};if(JSON.stringify(audit)!==before)throw new Error("QA evaluation mutated the source audit.");return result;}
return {VERSION,SEVERITIES,CATEGORIES,STATES,RULES,evaluate,readiness,applyStates};
});
