const test=require("node:test"),assert=require("node:assert/strict"),qa=require("../qa-rules.js"),pkg=require("../package-export.js");
function clean(){return {auditId:"audit-clean",schemaVersion:4,qaDeclarations:{fieldScopeReviewed:true,analysisScopeReviewed:true,utilityAnalysisNotRequired:true},qaFindingStates:[],site:{facilityName:"Clean"},systems:[],equipment:[],utilityAccounts:[],endUseModels:[],ecms:[],calculations:[],ecmPortfolios:[]};}
function codes(result){return new Set(result.findings.map(f=>f.ruleId));}
test("clean reviewed fixture is REPORT_READY and evaluation is deterministic/non-mutating",()=>{const a=clean(),before=JSON.stringify(a),x=qa.evaluate(a,{generatedAt:"2026-01-01T00:00:00Z"}),y=qa.evaluate(a,{generatedAt:"2026-01-01T00:00:00Z"});assert.equal(x.readiness,"REPORT_READY");assert.deepEqual(x,y);assert.equal(JSON.stringify(a),before)});
test("data relationships, duplicate IDs, measurement QA, and provenance produce stable findings",()=>{const a=clean();a.systems=[{systemRecordId:"s1",status:"Present"}];a.equipment=[{recordId:"e1",equipmentId:"E-1",systemRecordId:"missing",systemType:"HVAC",measurements:[{measurementId:"m1",parameter:"Calculated runtime",value:9000,unit:"",provenance:"Measured",method:"Calculated"}],photos:[]},{recordId:"e1",equipmentId:"E-2",systemType:"HVAC",measurements:[],photos:[]}];a.ecms=[{ecmId:"ECM-1",affectedEquipmentRecordIds:["gone"],existingCondition:"x",proposedImprovement:"y"}];const r=qa.evaluate(a),c=codes(r);for(const id of ["QA-DATA-001","QA-DATA-005","QA-DATA-006","QA-MEAS-002","QA-MEAS-004","QA-MEAS-006"])assert.ok(c.has(id),id);assert.equal(new Set(r.findings.map(f=>f.findingId)).size,r.findings.length)});
test("duplicate method flags collapse to one stable finding with retained evidence",()=>{const a=clean();a.ecms=[{ecmId:"E1",existingCondition:"x",proposedImprovement:"y"}];a.calculations=[{calculationId:"C1",ecmId:"E1",methodId:"m",methodVersion:"1",status:"Calculated",inputs:[],outputs:[],assumptions:["x"],qaFlags:[{code:"BOUNDARY_REVIEW",message:"one"},{code:"BOUNDARY_REVIEW",message:"two"}]}];const r=qa.evaluate(a),matches=r.findings.filter(f=>f.ruleId==="QA-CALC-005");assert.equal(matches.length,1);assert.equal(matches[0].evidence.length,2)});
test("photo Blob presence is behavioral context and missing payload is high severity",()=>{const a=clean();a.equipment=[{recordId:"e1",equipmentId:"E-1",systemType:"HVAC",measurements:[],photos:[{photoId:"p1",category:"Nameplate"}]}];assert.ok(codes(qa.evaluate(a,{storedPhotos:[]})).has("QA-PHOTO-001"));assert.ok(!codes(qa.evaluate(a,{storedPhotos:[{photoId:"p1",blob:new Blob(["x"])}]})).has("QA-PHOTO-001"))});
test("review state persists, accepted limitation is explicit, and corrected findings auto-clear",()=>{const a=clean();a.equipment=[{recordId:"e1",equipmentId:"E-1",systemType:"HVAC",measurements:[{measurementId:"m1",parameter:"Temperature",value:70,provenance:"Measured",instrument:"Calibrated thermometer"}],photos:[]}];let r=qa.evaluate(a),f=r.findings.find(x=>x.ruleId==="QA-MEAS-002");a.qaFindingStates=[{findingId:f.findingId,status:"REVIEWED",updatedAt:"t"}];assert.equal(qa.evaluate(a).findings.find(x=>x.findingId===f.findingId).status,"REVIEWED");a.qaFindingStates[0]={...a.qaFindingStates[0],status:"ACCEPTED_LIMITATION",engineerNote:"Instrument report omitted the displayed unit; retained as recorded."};r=qa.evaluate(a);assert.equal(r.findings.find(x=>x.findingId===f.findingId).status,"ACCEPTED_LIMITATION");assert.equal(r.readiness,"REPORT_READY_WITH_LIMITATIONS");a.equipment[0].measurements[0].unit="°F";r=qa.evaluate(a);assert.ok(!r.findings.some(x=>x.findingId===f.findingId));assert.equal(r.readiness,"REPORT_READY");assert.equal(r.acceptedLimitations.length,0)});
test("field and analysis readiness are separated",()=>{const a=clean();a.qaDeclarations.fieldScopeReviewed=false;assert.equal(qa.evaluate(a).readiness,"FIELD_INCOMPLETE");a.qaDeclarations.fieldScopeReviewed=true;a.calculations=[{calculationId:"c1",ecmId:"missing",methodId:"m",methodVersion:"1",inputs:[],outputs:[],status:"Needs Recalculation"}];assert.equal(qa.evaluate(a).readiness,"ANALYSIS_INCOMPLETE")});
test("utility QA reads analyzed account completeness rather than raw account fields",()=>{const a=clean();a.qaDeclarations.utilityAnalysisNotRequired=false;a.utilityAccounts=[{utilityAccountId:"u1",utilityType:"Electricity",bills:[{utilityBillId:"b1",utilityAccountId:"u1",billingMonth:"2026-01",usage:10,usageUnit:"kWh",cost:2}]}];assert.ok(codes(qa.evaluate(a)).has("QA-UTIL-001"));for(let i=2;i<=12;i++)a.utilityAccounts[0].bills.push({utilityBillId:`b${i}`,utilityAccountId:"u1",billingMonth:`2026-${String(i).padStart(2,"0")}`,usage:10,usageUnit:"kWh",cost:2});assert.ok(!codes(qa.evaluate(a)).has("QA-UTIL-001"))});
test("orphan Blobs, conflicting measurements, and manufacturer-source gaps are explicit",()=>{const a=clean();a.equipment=[{recordId:"e1",equipmentId:"E-1",systemType:"HVAC",photos:[],measurements:[{measurementId:"m1",parameter:"Flow",value:10,unit:"gpm",provenance:"Measured"},{measurementId:"m2",parameter:"Flow",value:20,unit:"gpm",provenance:"Measured"}]}];a.manufacturerPerformanceDatasets=[{performanceDatasetId:"pds1",manufacturer:"",sourceDocument:""}];const c=codes(qa.evaluate(a,{storedPhotos:[{photoId:"orphan",blob:new Blob(["x"])}]}));for(const id of ["QA-DATA-010","QA-MEAS-013","QA-PROV-002"])assert.ok(c.has(id),id)});
test("facility savings beyond utility boundaries and invalid economics are material QA",()=>{const a=clean();a.qaDeclarations.utilityAnalysisNotRequired=false;a.utilityAccounts=[{utilityAccountId:"u1",utilityType:"Electricity",bills:Array.from({length:12},(_,i)=>({utilityBillId:`b${i}`,utilityAccountId:"u1",billingMonth:`2026-${String(i+1).padStart(2,"0")}`,usage:100,usageUnit:"kWh",peakDemandKw:10,cost:20}))}];a.ecms=[{ecmId:"ECM-1",existingCondition:"old",proposedImprovement:"new",affectedEquipmentRecordIds:[],calculationIds:["c1"],implementationCost:1000,simplePaybackYears:2,costSavings:0}];a.calculations=[{calculationId:"c1",ecmId:"ECM-1",methodId:"m",methodVersion:"1",status:"Calculated",inputs:[],outputs:[{parameterId:"annualKwhSavings",displayName:"Annual kWh savings",value:2000,unit:"kWh/yr"},{parameterId:"demandSavings",displayName:"Demand savings",value:20,unit:"kW"}],assumptions:["Annual boundary"]}];const c=codes(qa.evaluate(a));assert.ok(c.has("QA-UTIL-004"));assert.ok(c.has("QA-ECON-002"));assert.ok(c.has("QA-ECM-003"))});
test("export includes canonical auditQa, manifest summary, and qa_findings CSV while integrity remains separate",async()=>{const a=clean();a.qaDeclarations.analysisScopeReviewed=false;const p=await pkg.prepare(a,[]),csv=await p.files.find(f=>f.path==="tables/qa_findings.csv").blob.text();assert.equal(p.manifest.integrity.status,"PASS");assert.equal(p.audit.auditQa.readiness,"REPORT_READY_WITH_LIMITATIONS");assert.equal(p.manifest.auditQaSummary.readiness,p.audit.auditQa.readiness);assert.match(csv,/QA-REPORT-001/)});
test("large deterministic audit evaluates within a practical synchronous bound",()=>{const a=clean();for(let i=0;i<1000;i++)a.equipment.push({recordId:`e${i}`,equipmentId:`E-${i}`,systemType:"HVAC",measurements:[{measurementId:`m${i}`,parameter:"Temperature",value:70,unit:"°F",provenance:"Measured",instrument:"T1"}],photos:[]});const start=Date.now(),r=qa.evaluate(a);assert.equal(r.readiness,"REPORT_READY");assert.ok(Date.now()-start<2000)});
