const test=require("node:test"),assert=require("node:assert/strict"),report=require("../report-engine.js"),pkg=require("../package-export.js");

function audit(){return {auditId:"audit-report",schemaVersion:4,updatedAt:"2026-08-23T10:00:00Z",site:{facilityName:"Golden Facility",buildingAreaSqFt:10000,buildingAreaProvenance:"Measured"},qaDeclarations:{fieldScopeReviewed:true,analysisScopeReviewed:true,utilityAnalysisNotRequired:true},qaFindingStates:[],systems:[{systemRecordId:"sys-1",systemType:"Lighting",status:"Present"}],equipment:[{recordId:"eq-1",equipmentId:"LTG-01",systemRecordId:"sys-1",systemType:"Lighting",measurements:[],photos:[{photoId:"photo-1",equipmentRecordId:"eq-1",category:"Overview",includeInReport:true,reportCaption:"Lighting system",reportSection:"building-systems",reportOrder:1,dataUrl:"data:image/png;base64,AAAA"}]}],utilityAccounts:[],endUseModels:[],ecms:[{ecmId:"ECM-01",title:"LED retrofit",affectedEquipmentRecordIds:["eq-1"],calculationIds:["calc-1"],implementationCost:10000,simplePaybackYears:2,annualKwhSavings:25000,annualCostSavings:5000,existingCondition:"Existing lighting",proposedImprovement:"LED"}],calculations:[{calculationId:"calc-1",ecmId:"ECM-01",methodId:"CALC-LTG-001",methodVersion:"1.1",status:"Calculated",equipmentRecordIds:["eq-1"],inputs:[],outputs:[{parameterId:"annualKwhSavings",value:25000,unit:"kWh/yr"}],assumptions:[],qaFlags:[]}],ecmPortfolios:[],aiReviews:[],reports:[]};}
function response(a=audit()){return {reportSchemaVersion:1,auditId:a.auditId,auditUpdatedAtUsed:a.updatedAt,title:"Draft Level 2 Report",sections:report.SECTION_TEMPLATE.map(s=>({...s,content:s.sectionId==="executive-summary"?"Calculated savings are presented from the canonical record.":"Based on available information.",sourceRecordIds:s.sectionId==="ecms"?["ECM-01","calc-1"]:[],unresolvedWarnings:[]})),tables:[{tableId:"ecm-summary",title:"ECM Summary",columns:["ECM","kWh/yr"],rows:[["ECM-01",25000],["Uncalculated",null]],sourceRecordIds:["ECM-01","calc-1"]}],figures:[{figureId:"fig-1",photoId:"photo-1",sectionId:"building-systems",caption:"Lighting system",order:1}],limitations:["Utility baseline not required for this fixture."],sourceReferences:["ECM-01","calc-1","photo-1"],numericClaims:[{metricId:"ecm.ECM-01.annualKwhSavings",value:25000,unit:"kWh/yr"},{metricId:"ecm.ECM-01.implementationCost",value:10000,unit:"$"}]};}

test("report request is traceable, versioned, ordered, and retains selected photos and limitations",()=>{const a=audit(),before=structuredClone(a),r=report.buildRequest(a,{appVersion:"6.2"});assert.equal(r.reportSchemaVersion,1);assert.equal(r.requestedStructure.length,14);assert.equal(r.selectedPhotos[0].photoId,"photo-1");assert.ok(r.canonicalMetrics.some(x=>x.metricId==="ecm.ECM-01.annualKwhSavings"));assert.deepEqual(a,before)});
test("wrong audit, malformed structure, and unsupported ECM calculation or photo references reject atomically",()=>{const a=audit();for(const mutate of [r=>r.auditId="wrong",r=>delete r.sections,r=>r.sections[0].sourceRecordIds=["ECM-404"],r=>r.tables[0].sourceRecordIds=["calc-404"],r=>r.figures[0].photoId="photo-404"]){const v=response(a);mutate(v);assert.equal(report.validateResponse(v,a).valid,false)}});
test("numeric validation accepts rounding and rejects unsupported or materially different claims",()=>{const a=audit(),rounded=response(a);rounded.numericClaims[0].value=25000.01;assert.equal(report.validateResponse(rounded,a).valid,true);const bad=response(a);bad.numericClaims[0].value=42000;assert.equal(report.validateResponse(bad,a).valid,false);const unknown=response(a);unknown.numericClaims[0].metricId="ecm.ECM-01.unsupported";assert.equal(report.validateResponse(unknown,a).valid,false)});
test("null table values stay null and are not converted to zero",()=>{const checked=report.validateResponse(response(),audit());assert.equal(checked.valid,true);assert.equal(checked.value.tables[0].rows[1][1],null)});
test("editing report narrative never mutates source audit",()=>{const a=audit(),before=structuredClone(a),draft=report.importResponse(response(a),a,{reportId:"report-1",importedAt:"t"}),edited=report.editSection(draft,"executive-summary","Engineer-edited narrative","t2");assert.equal(edited.sections[0].content,"Engineer-edited narrative");assert.deepEqual(a,before);assert.equal(a.calculations[0].outputs[0].value,25000)});
test("calculation and portfolio changes make an imported report stale",()=>{const a=audit(),draft=report.importResponse(response(a),a,{reportId:"report-1"});assert.equal(report.isStale(draft,a),false);a.calculations[0].outputs[0].value=24000;assert.equal(report.isStale(draft,a),true);const b=audit(),draft2=report.importResponse(response(b),b,{reportId:"report-2"});b.ecmPortfolios.push({portfolioId:"p1",ecmIds:["ECM-01"]});assert.equal(report.isStale(draft2,b),true)});
test("golden report preserves section order, facts, references, figures, limitations, HTML and print CSS",()=>{const a=audit(),draft=report.importResponse(response(a),a,{reportId:"golden"}),html=report.renderHtml(draft,a);assert.deepEqual(draft.sections.map(x=>x.sectionId),report.SECTION_TEMPLATE.map(x=>x.sectionId));assert.equal(draft.numericClaims[0].value,25000);assert.equal(draft.figures[0].photoId,"photo-1");assert.deepEqual(draft.limitations,["Utility baseline not required for this fixture."]);assert.match(html,/Draft Level 2 Report/);assert.match(html,/25000/);assert.match(html,/@media print/);assert.match(html,/Not calculated/)});
test("missing selected figure produces report integrity failure",()=>{const a=audit(),draft=report.importResponse(response(a),a,{reportId:"r"});a.equipment[0].photos=[];assert.equal(report.integrity(draft,a).status,"FAIL")});
test("professional package includes current report JSON, selected photo, and printable HTML without mutating the audit",async()=>{const a=audit(),draft=report.importResponse(response(a),a,{reportId:"r"});a.reports=[draft];const before=structuredClone(a),p=await pkg.prepare(a,[]),html=await p.files.find(f=>f.path==="report/report.html").blob.text();assert.ok(p.files.some(f=>f.path==="report/report.json"));assert.match(html,/<img src="\.\.\/photos\//);assert.equal(p.manifest.reportSummary.count,1);assert.equal(p.manifest.reportSummary.current,true);assert.equal(p.manifest.packageFormatVersion,10);assert.deepEqual(a,before)});
