const test=require("node:test"),assert=require("node:assert/strict"),U=require("../utility-analysis.js");
const bills=(accountId,count=12,{usage=1000,cost=200,unit="kWh",demand=50,startYear=2025}={})=>Array.from({length:count},(_,i)=>{const start=new Date(Date.UTC(startYear,i,1)),end=new Date(Date.UTC(startYear,i+1,0));return {utilityBillId:`${accountId}-b${i+1}`,utilityAccountId:accountId,billingStartDate:start.toISOString().slice(0,10),billingEndDate:end.toISOString().slice(0,10),billingMonth:end.toISOString().slice(0,7),usage,usageUnit:unit,peakDemandKw:demand,cost,energyCost:150,demandCost:30,fixedCharges:10,taxesOther:10};});
const account=(id,type="Electricity",options={})=>({utilityAccountId:id,utilityType:type,provider:"Test Utility",accountLabel:id,bills:bills(id,12,options)});

test("complete annual electricity, normalization, rates, EUI, demand and no mutation",()=>{const audit={site:{buildingAreaSqFt:10000,buildingAreaProvenance:"Measured drawings"},utilityAccounts:[account("e1")]},before=structuredClone(audit),r=U.analyze(audit),a=r.accountResults[0];assert.deepEqual(audit,before);assert.equal(a.completeness.status,"COMPLETE_12_MONTHS");assert.equal(a.annual.usage,12000);assert.equal(a.annual.cost,2400);assert.equal(a.annual.blendedRate,.2);assert.equal(a.maxDemandKw,50);assert.equal(r.totals.eui.electricKbtuPerSqFt,12000*3.412/10000);assert.equal(r.totals.demandIntensity.wattsPerSqFt,5);assert.equal(a.baseload.maturity,"SCREENING");});
test("gas conversion and multiple accounts aggregate only when all are complete",()=>{const audit={site:{buildingAreaSqFt:1000},utilityAccounts:[account("e1"),account("e2"),account("g1","Natural Gas",{usage:100,cost:80,unit:"therms",demand:null})]},r=U.analyze(audit);assert.equal(r.totals.byType.Electricity.annualUsage,24000);assert.equal(r.totals.byType["Natural Gas"].annualUsage,1200);assert.equal(r.totals.eui.gasKbtuPerSqFt,120);audit.utilityAccounts[1].bills.pop();const partial=U.analyze(audit);assert.equal(partial.totals.byType.Electricity.allAccountsComplete,false);assert.equal(partial.totals.eui.electricKbtuPerSqFt,null);assert.equal(partial.totals.totalUtilityCost,null);});
test("partial periods are not annualized and incomplete records stay partial",()=>{const a=account("e1");a.bills=a.bills.slice(0,7);const r=U.analyzeAccount(a);assert.equal(r.completeness.status,"PARTIAL");assert.equal(r.annual,null);assert.equal(r.periodTotals.usage,7000);const unlabeled=account("e2");unlabeled.bills.forEach(b=>{b.billingStartDate="";b.billingEndDate="";b.billingMonth="";});assert.equal(U.accountCompleteness(unlabeled).status,"PARTIAL");});
test("quality flags detect duplicates, overlap, gaps, invalid dates and units",()=>{const a=account("e1");a.bills[1].utilityBillId=a.bills[0].utilityBillId;a.bills[1].billingStartDate=a.bills[0].billingStartDate;a.bills[2].billingStartDate="bad";a.bills[3].usageUnit="MWh";const codes=U.analyzeAccount(a).completeness.flags.map(x=>x.code);for(const code of ["DUPLICATE_BILL_ID","OVERLAPPING_BILLS","BILLING_GAP","INVALID_BILLING_DATES","UNSUPPORTED_OR_AMBIGUOUS_UNIT"])assert.ok(codes.includes(code),code);});
test("legacy utility months migrate without inventing account metadata or dates",()=>{const audit={utility:{months:[{utilityMonthId:"m1",month:"2025-01",kwh:"100",kw:"20",electricCost:"30",therms:"5",gasCost:"6"}]}},accounts=U.legacyToAccounts(audit),e=accounts.find(x=>x.utilityType==="Electricity");assert.equal(accounts.length,2);assert.equal(e.provider,"");assert.equal(e.bills[0].billingStartDate,"");assert.equal(e.bills[0].usage,100);assert.equal(e.bills[0].migrationContext.exactDatesUnavailable,true);});
test("ECM QA compares calculated savings with complete baselines",()=>{const audit={utilityAccounts:[account("e1")],calculations:[{calculationId:"c1",status:"Calculated",outputs:[{parameterId:"annualKwhSavings",value:13000,unit:"kWh/yr"},{parameterId:"peakKwReduction",value:60,unit:"kW"}]}]},codes=U.analyze(audit).qaFlags.map(x=>x.code);assert.ok(codes.includes("ECM_KWH_EXCEEDS_BASELINE"));assert.ok(codes.includes("ECM_DEMAND_EXCEEDS_OBSERVED_PEAK"));});
test("CSV parser requires explicit mapping and preserves quoted values",()=>{const csv='Start,End,Use,Cost,Note\r\n2025-01-01,2025-01-31,100,"20.50","meter, west"';const rows=U.parseCsv(csv);assert.equal(rows[1][4],"meter, west");const mapped=U.mapCsvRows(csv,{billingStartDate:"Start",billingEndDate:"End",usage:"Use",cost:"Cost",usageUnit:"kWh"},{utilityAccountId:"e1"});assert.equal(mapped[0].usage,100);assert.equal(mapped[0].cost,20.5);assert.throws(()=>U.mapCsvRows(csv,{billingStartDate:"Start"},{utilityAccountId:"e1"}),/mapping missing/);});
test("missing area and conflicting entered rates are explicit QA flags",()=>{const audit={site:{},utility:{electricRate:.25},utilityAccounts:[account("e1")]},codes=U.analyze(audit).qaFlags.map(x=>x.code);assert.ok(codes.includes("EUI_REQUIRES_BUILDING_AREA"));assert.ok(codes.includes("DEMAND_INTENSITY_REQUIRES_BUILDING_AREA"));assert.ok(codes.includes("ENTERED_DERIVED_ELECTRIC_RATE_CONFLICT"));});
test("mixed water units and missing material values never produce an annual baseline",()=>{const water=account("w1","Water",{usage:100,cost:20,unit:"gallons",demand:null});water.bills[1].usageUnit="kgal";let r=U.analyzeAccount(water);assert.equal(r.annual,null);assert.ok(r.completeness.flags.some(x=>x.code==="INCONSISTENT_USAGE_UNITS"));const electric=account("e1");electric.bills[0].usage=null;r=U.analyzeAccount(electric);assert.equal(r.completeness.status,"PARTIAL");assert.equal(r.annual,null);});
test("empty utility data produces no false facility QA warnings",()=>{assert.deepEqual(U.analyze({site:{},utilityAccounts:[]}).qaFlags,[]);});
