const test=require("node:test"),assert=require("node:assert/strict"),engine=require("../calculations.js"),flow=require("../workflow.js");
const measurement=(id,value,source="Measured")=>({measurementId:id,parameter:"Fixture watts",value,numericValue:value,unit:"W",source});
const audit=()=>({auditId:"A1",utility:{electricRate:.22,rateProvenance:"Utility Bill"},equipmentGroups:[],calculations:[],equipment:[{recordId:"EQ1",equipmentId:"LTG-01",systemType:"Lighting",existingWatts:59,quantity:18,hoursAnnual:4100,fieldProvenance:{existingWatts:"Nameplate",quantity:"Measured",hoursAnnual:"BAS / Trend"},measurements:[],photos:[]}],ecms:[{ecmId:"ECM-01",title:"LED Retrofit",templateKey:"lighting_led",affectedEquipmentRecordIds:["EQ1"]}]});

test("method inputs are classified for field, analysis, or recommended timing",()=>{const m=engine.METHOD_REGISTRY["CALC-LTG-001"];assert.equal(m.inputs.find(x=>x.parameterId==="existingFixtureWatts").timing,"FIELD_REQUIRED");assert.equal(m.inputs.find(x=>x.parameterId==="proposedFixtureWatts").timing,"ANALYSIS_REQUIRED");assert.ok(Object.values(engine.METHOD_REGISTRY).flatMap(x=>x.inputs).every(x=>["FIELD_REQUIRED","ANALYSIS_REQUIRED","RECOMMENDED"].includes(x.timing)))});
test("template creates the routine calculation recipe",()=>{const a=audit();flow.ensureRecipe(a.ecms[0]);assert.deepEqual(a.ecms[0].analysisRecipe.methodIds,["CALC-LTG-001"])});
test("auto-binding reuses structured equipment values and preserves provenance",()=>{const a=audit(),m=engine.METHOD_REGISTRY["CALC-LTG-001"],b=flow.bindInput(a,a.ecms[0],m.inputs[0]);assert.equal(b.selected.value,59);assert.equal(b.selected.sourceRecordId,"EQ1");assert.equal(b.selected.provenance,"Nameplate");assert.equal(b.selected.evidenceLevel,"A")});
test("preferred source selection chooses measurement over estimate and surfaces conflict",()=>{const a=audit();a.equipment[0].fieldProvenance.existingWatts="Estimated";a.equipment[0].measurements=[measurement("M1",57)];const def=engine.METHOD_REGISTRY["CALC-LTG-001"].inputs[0],b=flow.bindInput(a,a.ecms[0],def);assert.equal(b.selected.sourceRecordId,"M1");assert.equal(b.conflict,true);assert.equal(b.requiresSelection,false)});
test("equal-priority conflicting measurements require explicit selection",()=>{const a=audit();a.equipment[0].measurements=[measurement("M1",57),measurement("M2",61)];const b=flow.bindInput(a,a.ecms[0],engine.METHOD_REGISTRY["CALC-LTG-001"].inputs[0]);assert.equal(b.selected,null);assert.equal(b.requiresSelection,true)});
test("binding never mutates source audit records",()=>{const a=audit(),before=structuredClone(a);flow.engineeringReadiness(a,a.ecms[0],engine);assert.deepEqual(a,before)});
test("one measurement can independently support multiple ECMs",()=>{const a=audit();a.equipment[0].measurements=[measurement("M18",57)];a.ecms.push({...a.ecms[0],ecmId:"ECM-02"});const def=engine.METHOD_REGISTRY["CALC-LTG-001"].inputs[0];assert.equal(flow.bindInput(a,a.ecms[0],def).selected.sourceRecordId,"M18");assert.equal(flow.bindInput(a,a.ecms[1],def).selected.sourceRecordId,"M18");assert.equal(a.equipment[0].measurements.length,1)});
test("field-complete ECM remains calculation-not-ready for proposed office input",()=>{const a=audit(),r=flow.engineeringReadiness(a,a.ecms[0],engine);assert.equal(r.fieldRequiredComplete,true);assert.equal(r.status,"NEEDS_OFFICE_INPUT");assert.match(r.missingAnalysisInputs.join(" "),/Proposed Fixture Input/)});
test("missing proposed data does not reduce field documentation completeness",()=>{const a=audit(),r=flow.engineeringReadiness(a,a.ecms[0],engine);assert.equal(r.missingFieldInputs.length,0);assert.ok(r.missingAnalysisInputs.length>0)});
test("analysis queue categorizes office input and stale calculations",()=>{const a=audit();assert.equal(flow.analysisQueue(a,engine).NEEDS_OFFICE_INPUT.length,1);a.calculations=[{ecmId:"ECM-01",status:"Needs Recalculation"}];assert.equal(flow.analysisQueue(a,engine).NEEDS_RECALCULATION.length,1)});
test("field exit review excludes office-only inputs",()=>{const a=audit(),items=flow.fieldExitReview(a,engine);assert.equal(items.length,0);delete a.equipment[0].existingWatts;assert.match(flow.fieldExitReview(a,engine)[0].label,/Existing Fixture Input/)});
test("representative groups preserve members, sample, and downgrade population provenance",()=>{const a=audit();a.equipment[0].measurements=[measurement("M1",57)];a.equipmentGroups=[{groupId:"G1",name:"Lighting A",equipmentRecordIds:["EQ1"],sampling:{populationSize:126,sampleSize:1,sampledEquipmentRecordIds:["EQ1"],representativeConfirmed:true}}];a.ecms[0].equipmentGroupId="G1";const b=flow.bindInput(a,a.ecms[0],engine.METHOD_REGISTRY["CALC-LTG-001"].inputs[0]);assert.equal(b.selected.provenance,"Estimated");assert.equal(b.selected.evidenceLevel,"C");assert.match(b.selected.sourceDescription,/representative sample 1\/126/);assert.deepEqual(flow.associatedIds(a,a.ecms[0]),["EQ1"])});
test("unconfirmed sampling never changes measured provenance",()=>{const a=audit();a.equipment[0].measurements=[measurement("M1",57)];a.equipmentGroups=[{groupId:"G1",equipmentRecordIds:["EQ1"],sampling:{populationSize:126,sampleSize:1,sampledEquipmentRecordIds:["EQ1"],representativeConfirmed:false}}];a.ecms[0].equipmentGroupId="G1";assert.equal(flow.bindInput(a,a.ecms[0],engine.METHOD_REGISTRY["CALC-LTG-001"].inputs[0]).selected.provenance,"Measured")});
test("export includes derived readiness before a calculation exists",()=>{const a=audit(),x=flow.exportReadiness(a,engine)[0];assert.equal(x.methodIds[0],"CALC-LTG-001");assert.equal(x.status,"NEEDS_OFFICE_INPUT");assert.equal(x.fieldDataComplete,true);assert.match(x.missingAnalysisInputs.join(" "),/Proposed/)});
test("validation-only recipe reports missing onsite evidence before validation status",()=>{const a=audit();a.ecms[0]={ecmId:"ECM-02",title:"Economizer",templateKey:"hvac_economizer",affectedEquipmentRecordIds:["EQ1"]};const r=flow.engineeringReadiness(a,a.ecms[0],engine);assert.equal(r.status,"MISSING_FIELD_DATA");assert.ok(r.missingFieldInputs.length>0)});
